/* LIBPICMAN - The PICMAN Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * picmangradientselect_pdb.c
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#include "config.h"

#include "picman.h"


/**
 * SECTION: picmangradientselect
 * @title: picmangradientselect
 * @short_description: Functions providing a gradient selection dialog.
 *
 * Functions providing a gradient selection dialog.
 **/


/**
 * picman_gradients_popup:
 * @gradient_callback: The callback PDB proc to call when gradient selection is made.
 * @popup_title: Title of the gradient selection dialog.
 * @initial_gradient: The name of the gradient to set as the first selected.
 * @sample_size: Size of the sample to return when the gradient is changed.
 *
 * Invokes the Picman gradients selection.
 *
 * This procedure opens the gradient selection dialog.
 *
 * Returns: TRUE on success.
 **/
gboolean
picman_gradients_popup (const gchar *gradient_callback,
                      const gchar *popup_title,
                      const gchar *initial_gradient,
                      gint         sample_size)
{
  PicmanParam *return_vals;
  gint nreturn_vals;
  gboolean success = TRUE;

  return_vals = picman_run_procedure ("picman-gradients-popup",
                                    &nreturn_vals,
                                    PICMAN_PDB_STRING, gradient_callback,
                                    PICMAN_PDB_STRING, popup_title,
                                    PICMAN_PDB_STRING, initial_gradient,
                                    PICMAN_PDB_INT32, sample_size,
                                    PICMAN_PDB_END);

  success = return_vals[0].data.d_status == PICMAN_PDB_SUCCESS;

  picman_destroy_params (return_vals, nreturn_vals);

  return success;
}

/**
 * picman_gradients_close_popup:
 * @gradient_callback: The name of the callback registered for this pop-up.
 *
 * Close the gradient selection dialog.
 *
 * This procedure closes an opened gradient selection dialog.
 *
 * Returns: TRUE on success.
 **/
gboolean
picman_gradients_close_popup (const gchar *gradient_callback)
{
  PicmanParam *return_vals;
  gint nreturn_vals;
  gboolean success = TRUE;

  return_vals = picman_run_procedure ("picman-gradients-close-popup",
                                    &nreturn_vals,
                                    PICMAN_PDB_STRING, gradient_callback,
                                    PICMAN_PDB_END);

  success = return_vals[0].data.d_status == PICMAN_PDB_SUCCESS;

  picman_destroy_params (return_vals, nreturn_vals);

  return success;
}

/**
 * picman_gradients_set_popup:
 * @gradient_callback: The name of the callback registered for this pop-up.
 * @gradient_name: The name of the gradient to set as selected.
 *
 * Sets the current gradient in a gradient selection dialog.
 *
 * Sets the current gradient in a gradient selection dialog.
 *
 * Returns: TRUE on success.
 **/
gboolean
picman_gradients_set_popup (const gchar *gradient_callback,
                          const gchar *gradient_name)
{
  PicmanParam *return_vals;
  gint nreturn_vals;
  gboolean success = TRUE;

  return_vals = picman_run_procedure ("picman-gradients-set-popup",
                                    &nreturn_vals,
                                    PICMAN_PDB_STRING, gradient_callback,
                                    PICMAN_PDB_STRING, gradient_name,
                                    PICMAN_PDB_END);

  success = return_vals[0].data.d_status == PICMAN_PDB_SUCCESS;

  picman_destroy_params (return_vals, nreturn_vals);

  return success;
}
