/* LIBPICMAN - The PICMAN Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * picmanfloatingsel_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__PICMAN_H_INSIDE__) && !defined (PICMAN_COMPILATION)
#error "Only <libpicman/picman.h> can be included directly."
#endif

#ifndef __PICMAN_FLOATING_SEL_PDB_H__
#define __PICMAN_FLOATING_SEL_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


gboolean picman_floating_sel_remove   (gint32   floating_sel_ID);
gboolean picman_floating_sel_anchor   (gint32   floating_sel_ID);
gboolean picman_floating_sel_to_layer (gint32   floating_sel_ID);
gboolean picman_floating_sel_attach   (gint32   layer_ID,
                                     gint32   drawable_ID);
PICMAN_DEPRECATED
gboolean picman_floating_sel_rigor    (gint32   floating_sel_ID,
                                     gboolean undo);
PICMAN_DEPRECATED
gboolean picman_floating_sel_relax    (gint32   floating_sel_ID,
                                     gboolean undo);


G_END_DECLS

#endif /* __PICMAN_FLOATING_SEL_PDB_H__ */
