/* PICMAN - The GNU Image Manipulation Program
 * Copyright (C) 1995 Spencer Kimball and Peter Mattis
 *
 * picmanhelp-ids.h
 * Copyright (C) 2003 Michael Natterer <mitch@picman.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __PICMAN_HELP_IDS_H__
#define __PICMAN_HELP_IDS_H__


#define PICMAN_HELP_MAIN                            "picman-main"

#define PICMAN_HELP_FILE_NEW                        "picman-file-new"
#define PICMAN_HELP_FILE_OPEN                       "picman-file-open"
#define PICMAN_HELP_FILE_OPEN_AS_LAYER              "picman-file-open-as-layer"
#define PICMAN_HELP_FILE_OPEN_LOCATION              "picman-file-open-location"
#define PICMAN_HELP_FILE_OPEN_BY_EXTENSION          "picman-file-open-by-extension"
#define PICMAN_HELP_FILE_OPEN_RECENT                "picman-file-open-recent"
#define PICMAN_HELP_FILE_SAVE                       "picman-file-save"
#define PICMAN_HELP_FILE_SAVE_AS                    "picman-file-save-as"
#define PICMAN_HELP_FILE_SAVE_A_COPY                "picman-file-save-a-copy"
#define PICMAN_HELP_FILE_SAVE_BY_EXTENSION          "picman-file-save-by-extension"
#define PICMAN_HELP_FILE_EXPORT                     "picman-file-export"
#define PICMAN_HELP_FILE_EXPORT_TO                  "picman-file-export-to"
#define PICMAN_HELP_FILE_OVERWRITE                  "picman-file-overwrite"
#define PICMAN_HELP_FILE_SAVE_AS_TEMPLATE           "picman-file-save-as-template"
#define PICMAN_HELP_FILE_REVERT                     "picman-file-revert"
#define PICMAN_HELP_FILE_CLOSE                      "picman-file-close"
#define PICMAN_HELP_FILE_CLOSE_ALL                  "picman-file-close-all"
#define PICMAN_HELP_FILE_CREATE_TEMPLATE            "picman-file-save-as-template" /* Update string along with picman-help-2 */
#define PICMAN_HELP_FILE_QUIT                       "picman-file-quit"

#define PICMAN_HELP_EDIT_UNDO                       "picman-edit-undo"
#define PICMAN_HELP_EDIT_REDO                       "picman-edit-redo"
#define PICMAN_HELP_EDIT_STRONG_UNDO                "picman-edit-strong-undo"
#define PICMAN_HELP_EDIT_STRONG_REDO                "picman-edit-strong-redo"
#define PICMAN_HELP_EDIT_UNDO_CLEAR                 "picman-edit-undo-clear"
#define PICMAN_HELP_EDIT_FADE                       "picman-edit-fade"
#define PICMAN_HELP_EDIT_CUT                        "picman-edit-cut"
#define PICMAN_HELP_EDIT_COPY                       "picman-edit-copy"
#define PICMAN_HELP_EDIT_COPY_VISIBLE               "picman-edit-copy-visible"
#define PICMAN_HELP_EDIT_PASTE                      "picman-edit-paste"
#define PICMAN_HELP_EDIT_PASTE_INTO                 "picman-edit-paste-into"
#define PICMAN_HELP_EDIT_PASTE_AS_NEW               "picman-edit-paste-as-new"
#define PICMAN_HELP_EDIT_PASTE_AS_NEW_LAYER         "picman-edit-paste-as-new-layer"
#define PICMAN_HELP_EDIT_CLEAR                      "picman-edit-clear"
#define PICMAN_HELP_EDIT_FILL_FG                    "picman-edit-fill-fg"
#define PICMAN_HELP_EDIT_FILL_BG                    "picman-edit-fill-bg"
#define PICMAN_HELP_EDIT_FILL_PATTERN               "picman-edit-fill-pattern"

#define PICMAN_HELP_SELECTION_DIALOG                "picman-selection-dialog"
#define PICMAN_HELP_SELECTION_ALL                   "picman-selection-all"
#define PICMAN_HELP_SELECTION_NONE                  "picman-selection-none"
#define PICMAN_HELP_SELECTION_INVERT                "picman-selection-invert"
#define PICMAN_HELP_SELECTION_FLOAT                 "picman-selection-float"
#define PICMAN_HELP_SELECTION_FEATHER               "picman-selection-feather"
#define PICMAN_HELP_SELECTION_SHARPEN               "picman-selection-sharpen"
#define PICMAN_HELP_SELECTION_SHRINK                "picman-selection-shrink"
#define PICMAN_HELP_SELECTION_GROW                  "picman-selection-grow"
#define PICMAN_HELP_SELECTION_BORDER                "picman-selection-border"
#define PICMAN_HELP_SELECTION_STROKE                "picman-selection-stroke"
#define PICMAN_HELP_SELECTION_TO_CHANNEL            "picman-selection-to-channel"
#define PICMAN_HELP_SELECTION_TO_PATH               "picman-selection-to-path"

#define PICMAN_HELP_VIEW_NEW                        "picman-view-new"
#define PICMAN_HELP_VIEW_DOT_FOR_DOT                "picman-view-dot-for-dot"
#define PICMAN_HELP_VIEW_ZOOM_REVERT                "picman-view-zoom-revert"
#define PICMAN_HELP_VIEW_ZOOM_OUT                   "picman-view-zoom-out"
#define PICMAN_HELP_VIEW_ZOOM_IN                    "picman-view-zoom-in"
#define PICMAN_HELP_VIEW_ZOOM_100                   "picman-view-zoom-100"
#define PICMAN_HELP_VIEW_ZOOM_FIT_IN                "picman-view-zoom-fit-in"
#define PICMAN_HELP_VIEW_ZOOM_FILL                  "picman-view-zoom-fill"
#define PICMAN_HELP_VIEW_ZOOM_OTHER                 "picman-view-zoom-other"
#define PICMAN_HELP_VIEW_ROTATE_RESET               "picman-view-rotate-reset"
#define PICMAN_HELP_VIEW_ROTATE_90                  "picman-view-rotate-90"
#define PICMAN_HELP_VIEW_ROTATE_180                 "picman-view-rotate-180"
#define PICMAN_HELP_VIEW_ROTATE_270                 "picman-view-rotate-270"
#define PICMAN_HELP_VIEW_ROTATE_OTHER               "picman-view-rotate-other"
#define PICMAN_HELP_VIEW_SHOW_SELECTION             "picman-view-show-selection"
#define PICMAN_HELP_VIEW_SHOW_LAYER_BOUNDARY        "picman-view-show-layer-boundary"
#define PICMAN_HELP_VIEW_SHOW_GUIDES                "picman-view-show-guides"
#define PICMAN_HELP_VIEW_SHOW_GRID                  "picman-view-show-grid"
#define PICMAN_HELP_VIEW_SHOW_SAMPLE_POINTS         "picman-view-show-sample-points"
#define PICMAN_HELP_VIEW_SNAP_TO_GUIDES             "picman-view-snap-to-guides"
#define PICMAN_HELP_VIEW_SNAP_TO_GRID               "picman-view-snap-to-grid"
#define PICMAN_HELP_VIEW_SNAP_TO_CANVAS             "picman-view-snap-to-canvas"
#define PICMAN_HELP_VIEW_SNAP_TO_VECTORS            "picman-view-snap-to-vectors"
#define PICMAN_HELP_VIEW_SHOW_MENUBAR               "picman-view-show-menubar"
#define PICMAN_HELP_VIEW_SHOW_RULERS                "picman-view-show-rulers"
#define PICMAN_HELP_VIEW_SHOW_SCROLLBARS            "picman-view-show-scrollbars"
#define PICMAN_HELP_VIEW_SHOW_STATUSBAR             "picman-view-show-statusbar"
#define PICMAN_HELP_VIEW_PADDING_COLOR              "picman-view-padding-color"
#define PICMAN_HELP_VIEW_SHRINK_WRAP                "picman-view-shrink-wrap"
#define PICMAN_HELP_VIEW_FULLSCREEN                 "picman-view-fullscreen"
#define PICMAN_HELP_VIEW_CHANGE_SCREEN              "picman-view-change-screen"

#define PICMAN_HELP_IMAGE_WINDOW                    "picman-image-window"
#define PICMAN_HELP_IMAGE_WINDOW_ORIGIN             "picman-image-window-origin"
#define PICMAN_HELP_IMAGE_WINDOW_ZOOM_FOLLOW_BUTTON "picman-image-window-zoom-follow-button"
#define PICMAN_HELP_IMAGE_WINDOW_QUICK_MASK_BUTTON  "picman-image-window-quick-mask-button"
#define PICMAN_HELP_IMAGE_WINDOW_NAV_BUTTON         "picman-image-window-nav-button"
#define PICMAN_HELP_IMAGE_WINDOW_RULER              "picman-image-window-ruler"
#define PICMAN_HELP_IMAGE_WINDOW_STATUS_BAR         "picman-image-window-status-bar"


#define PICMAN_HELP_IMAGE_DIALOG                    "picman-image-dialog"
#define PICMAN_HELP_IMAGE_CONVERT_RGB               "picman-image-convert-rgb"
#define PICMAN_HELP_IMAGE_CONVERT_GRAYSCALE         "picman-image-convert-grayscale"
#define PICMAN_HELP_IMAGE_CONVERT_INDEXED           "picman-image-convert-indexed"
#define PICMAN_HELP_IMAGE_CONVERT_U8                "picman-image-convert-u8"
#define PICMAN_HELP_IMAGE_CONVERT_U16               "picman-image-convert-u16"
#define PICMAN_HELP_IMAGE_CONVERT_U32               "picman-image-convert-u32"
#define PICMAN_HELP_IMAGE_CONVERT_HALF              "picman-image-convert-half"
#define PICMAN_HELP_IMAGE_CONVERT_FLOAT             "picman-image-convert-float"
#define PICMAN_HELP_IMAGE_CONVERT_PRECISION         "picman-image-convert-precision"
#define PICMAN_HELP_IMAGE_FLIP_HORIZONTAL           "picman-image-flip-horizontal"
#define PICMAN_HELP_IMAGE_FLIP_VERTICAL             "picman-image-flip-vertical"
#define PICMAN_HELP_IMAGE_ROTATE_90                 "picman-image-rotate-90"
#define PICMAN_HELP_IMAGE_ROTATE_180                "picman-image-rotate-180"
#define PICMAN_HELP_IMAGE_ROTATE_270                "picman-image-rotate-270"
#define PICMAN_HELP_IMAGE_RESIZE                    "picman-image-resize"
#define PICMAN_HELP_IMAGE_RESIZE_TO_LAYERS          "picman-image-resize-to-layers"
#define PICMAN_HELP_IMAGE_RESIZE_TO_SELECTION       "picman-image-resize-to-selection"
#define PICMAN_HELP_IMAGE_PRINT_SIZE                "picman-image-print-size"
#define PICMAN_HELP_IMAGE_SCALE                     "picman-image-scale"
#define PICMAN_HELP_IMAGE_SCALE_WARNING             "picman-image-scale-warning"
#define PICMAN_HELP_IMAGE_CROP                      "picman-image-crop"
#define PICMAN_HELP_IMAGE_DUPLICATE                 "picman-image-duplicate"
#define PICMAN_HELP_IMAGE_MERGE_LAYERS              "picman-image-merge-layers"
#define PICMAN_HELP_IMAGE_FLATTEN                   "picman-image-flatten"
#define PICMAN_HELP_IMAGE_GRID                      "picman-image-grid"
#define PICMAN_HELP_IMAGE_PROPERTIES                "picman-image-properties"

#define PICMAN_HELP_LAYER_DIALOG                    "picman-layer-dialog"
#define PICMAN_HELP_LAYER_DIALOG_PAINT_MODE_MENU    "picman-layer-dialog-paint-mode-menu"
#define PICMAN_HELP_LAYER_DIALOG_OPACITY_SCALE      "picman-layer-dialog-opacity-scale"

#define PICMAN_HELP_LAYER_NEW                       "picman-layer-new"
#define PICMAN_HELP_LAYER_NEW_FROM_VISIBLE          "picman-layer-new-from-visible"
#define PICMAN_HELP_LAYER_DUPLICATE                 "picman-layer-duplicate"
#define PICMAN_HELP_LAYER_ANCHOR                    "picman-layer-anchor"
#define PICMAN_HELP_LAYER_MERGE_DOWN                "picman-layer-merge-down"
#define PICMAN_HELP_LAYER_MERGE_GROUP               "picman-layer-merge-group"
#define PICMAN_HELP_LAYER_DELETE                    "picman-layer-delete"
#define PICMAN_HELP_LAYER_TEXT_DISCARD              "picman-layer-text-discard"
#define PICMAN_HELP_LAYER_TEXT_TO_PATH              "picman-layer-text-to-path"
#define PICMAN_HELP_LAYER_TEXT_ALONG_PATH           "picman-layer-text-along-path"
#define PICMAN_HELP_LAYER_PREVIOUS                  "picman-layer-previous"
#define PICMAN_HELP_LAYER_NEXT                      "picman-layer-next"
#define PICMAN_HELP_LAYER_TOP                       "picman-layer-top"
#define PICMAN_HELP_LAYER_BOTTOM                    "picman-layer-bottom"
#define PICMAN_HELP_LAYER_RAISE                     "picman-layer-raise"
#define PICMAN_HELP_LAYER_RAISE_TO_TOP              "picman-layer-raise-to-top"
#define PICMAN_HELP_LAYER_LOWER                     "picman-layer-lower"
#define PICMAN_HELP_LAYER_LOWER_TO_BOTTOM           "picman-layer-lower-to-bottom"
#define PICMAN_HELP_LAYER_INVERT                    "picman-layer-invert"
#define PICMAN_HELP_LAYER_WHITE_BALANCE             "picman-layer-white-balance"
#define PICMAN_HELP_LAYER_EQUALIZE                  "picman-layer-equalize"
#define PICMAN_HELP_LAYER_VISIBLE                   "picman-layer-visible"
#define PICMAN_HELP_LAYER_LINKED                    "picman-layer-linked"
#define PICMAN_HELP_LAYER_OPACITY                   "picman-layer-opacity"
#define PICMAN_HELP_LAYER_MODE                      "picman-layer-mode"
#define PICMAN_HELP_LAYER_LOCK_ALPHA                "picman-layer-lock-alpha"
#define PICMAN_HELP_LAYER_LOCK_PIXELS               "picman-layer-lock-pixels"
#define PICMAN_HELP_LAYER_LOCK_POSITION             "picman-layer-lock-position"
#define PICMAN_HELP_LAYER_MASK_ADD                  "picman-layer-mask-add"
#define PICMAN_HELP_LAYER_MASK_APPLY                "picman-layer-mask-apply"
#define PICMAN_HELP_LAYER_MASK_DELETE               "picman-layer-mask-delete"
#define PICMAN_HELP_LAYER_MASK_EDIT                 "picman-layer-mask-edit"
#define PICMAN_HELP_LAYER_MASK_SHOW                 "picman-layer-mask-show"
#define PICMAN_HELP_LAYER_MASK_DISABLE              "picman-layer-mask-disable"
#define PICMAN_HELP_LAYER_MASK_SELECTION_REPLACE    "picman-layer-mask-selection-replace"
#define PICMAN_HELP_LAYER_MASK_SELECTION_ADD        "picman-layer-mask-selection-add"
#define PICMAN_HELP_LAYER_MASK_SELECTION_SUBTRACT   "picman-layer-mask-selection-subtract"
#define PICMAN_HELP_LAYER_MASK_SELECTION_INTERSECT  "picman-layer-mask-selection-intersect"
#define PICMAN_HELP_LAYER_ALPHA_ADD                 "picman-layer-alpha-add"
#define PICMAN_HELP_LAYER_ALPHA_REMOVE              "picman-layer-alpha-remove"
#define PICMAN_HELP_LAYER_ALPHA_SELECTION_REPLACE   "picman-layer-alpha-selection-replace"
#define PICMAN_HELP_LAYER_ALPHA_SELECTION_ADD       "picman-layer-alpha-selection-add"
#define PICMAN_HELP_LAYER_ALPHA_SELECTION_SUBTRACT  "picman-layer-alpha-selection-subtract"
#define PICMAN_HELP_LAYER_ALPHA_SELECTION_INTERSECT "picman-layer-alpha-selection-intersect"
#define PICMAN_HELP_LAYER_FLIP_HORIZONTAL           "picman-layer-flip-horizontal"
#define PICMAN_HELP_LAYER_FLIP_VERTICAL             "picman-layer-flip-vertical"
#define PICMAN_HELP_LAYER_ROTATE_90                 "picman-layer-rotate-90"
#define PICMAN_HELP_LAYER_ROTATE_180                "picman-layer-rotate-180"
#define PICMAN_HELP_LAYER_ROTATE_270                "picman-layer-rotate-270"
#define PICMAN_HELP_LAYER_OFFSET                    "picman-layer-offset"
#define PICMAN_HELP_LAYER_RESIZE                    "picman-layer-resize"
#define PICMAN_HELP_LAYER_RESIZE_TO_IMAGE           "picman-layer-resize-to-image"
#define PICMAN_HELP_LAYER_SCALE                     "picman-layer-scale"
#define PICMAN_HELP_LAYER_CROP                      "picman-layer-crop"
#define PICMAN_HELP_LAYER_EDIT                      "picman-layer-edit"

#define PICMAN_HELP_CHANNEL_DIALOG                  "picman-channel-dialog"
#define PICMAN_HELP_CHANNEL_NEW                     "picman-channel-new"
#define PICMAN_HELP_CHANNEL_RAISE                   "picman-channel-raise"
#define PICMAN_HELP_CHANNEL_RAISE_TO_TOP            "picman-channel-raise-to-top"
#define PICMAN_HELP_CHANNEL_LOWER                   "picman-channel-lower"
#define PICMAN_HELP_CHANNEL_LOWER_TO_BOTTOM         "picman-channel-lower-to-bottom"
#define PICMAN_HELP_CHANNEL_DUPLICATE               "picman-channel-duplicate"
#define PICMAN_HELP_CHANNEL_DELETE                  "picman-channel-delete"
#define PICMAN_HELP_CHANNEL_LOCK_PIXELS             "picman-channel-lock-pixels"
#define PICMAN_HELP_CHANNEL_LOCK_POSITION           "picman-channel-lock-position"
#define PICMAN_HELP_CHANNEL_SELECTION_REPLACE       "picman-channel-selection-replace"
#define PICMAN_HELP_CHANNEL_SELECTION_ADD           "picman-channel-selection-add"
#define PICMAN_HELP_CHANNEL_SELECTION_SUBTRACT      "picman-channel-selection-subtract"
#define PICMAN_HELP_CHANNEL_SELECTION_INTERSECT     "picman-channel-selection-intersect"
#define PICMAN_HELP_CHANNEL_EDIT                    "picman-channel-edit"

#define PICMAN_HELP_QUICK_MASK                      "picman-quick-mask"
#define PICMAN_HELP_QUICK_MASK_TOGGLE               "picman-quick-mask-toggle"
#define PICMAN_HELP_QUICK_MASK_INVERT               "picman-quick-mask-invert"
#define PICMAN_HELP_QUICK_MASK_EDIT                 "picman-quick-mask-edit"

#define PICMAN_HELP_PATH_DIALOG                     "picman-path-dialog"
#define PICMAN_HELP_PATH_NEW                        "picman-path-new"
#define PICMAN_HELP_PATH_RAISE                      "picman-path-raise"
#define PICMAN_HELP_PATH_RAISE_TO_TOP               "picman-path-raise-to-top"
#define PICMAN_HELP_PATH_LOWER                      "picman-path-lower"
#define PICMAN_HELP_PATH_LOWER_TO_BOTTOM            "picman-path-lower-to-bottom"
#define PICMAN_HELP_PATH_DUPLICATE                  "picman-path-duplicate"
#define PICMAN_HELP_PATH_DELETE                     "picman-path-delete"
#define PICMAN_HELP_PATH_MERGE_VISIBLE              "picman-path-merge-visible"
#define PICMAN_HELP_PATH_VISIBLE                    "picman-path-visible"
#define PICMAN_HELP_PATH_LINKED                     "picman-path-linked"
#define PICMAN_HELP_PATH_LOCK_STROKES               "picman-path-lock-strokes"
#define PICMAN_HELP_PATH_LOCK_POSITION              "picman-path-lock-position"
#define PICMAN_HELP_PATH_SELECTION_REPLACE          "picman-path-selection-replace"
#define PICMAN_HELP_PATH_SELECTION_ADD              "picman-path-selection-add"
#define PICMAN_HELP_PATH_SELECTION_SUBTRACT         "picman-path-selection-subtract"
#define PICMAN_HELP_PATH_SELECTION_INTERSECT        "picman-path-selection-intersect"
#define PICMAN_HELP_PATH_STROKE                     "picman-path-stroke"
#define PICMAN_HELP_PATH_COPY                       "picman-path-copy"
#define PICMAN_HELP_PATH_PASTE                      "picman-path-paste"
#define PICMAN_HELP_PATH_IMPORT                     "picman-path-import"
#define PICMAN_HELP_PATH_EXPORT                     "picman-path-export"
#define PICMAN_HELP_PATH_EDIT                       "picman-path-edit"

#define PICMAN_HELP_TOOLS_DIALOG                    "picman-tools-dialog"

#define PICMAN_HELP_TOOL_AIRBRUSH                   "picman-tool-airbrush"
#define PICMAN_HELP_TOOL_ALIGN                      "picman-tool-align"
#define PICMAN_HELP_TOOL_BLEND                      "picman-tool-blend"
#define PICMAN_HELP_TOOL_BRIGHTNESS_CONTRAST        "picman-tool-brightness-contrast"
#define PICMAN_HELP_TOOL_BUCKET_FILL                "picman-tool-bucket-fill"
#define PICMAN_HELP_TOOL_BY_COLOR_SELECT            "picman-tool-by-color-select"
#define PICMAN_HELP_TOOL_CAGE                       "picman-tool-cage"
#define PICMAN_HELP_TOOL_CLONE                      "picman-tool-clone"
#define PICMAN_HELP_TOOL_COLORIZE                   "picman-tool-colorize"
#define PICMAN_HELP_TOOL_COLOR_BALANCE              "picman-tool-color-balance"
#define PICMAN_HELP_TOOL_COLOR_PICKER               "picman-tool-color-picker"
#define PICMAN_HELP_TOOL_CONVOLVE                   "picman-tool-convolve"
#define PICMAN_HELP_TOOL_CROP                       "picman-tool-crop"
#define PICMAN_HELP_TOOL_CURVES                     "picman-tool-curves"
#define PICMAN_HELP_TOOL_CURVES                     "picman-tool-curves"
#define PICMAN_HELP_TOOL_DESATURATE                 "picman-tool-desaturate"
#define PICMAN_HELP_TOOL_DODGE_BURN                 "picman-tool-dodge-burn"
#define PICMAN_HELP_TOOL_ELLIPSE_SELECT             "picman-tool-ellipse-select"
#define PICMAN_HELP_TOOL_ERASER                     "picman-tool-eraser"
#define PICMAN_HELP_TOOL_FLIP                       "picman-tool-flip"
#define PICMAN_HELP_TOOL_FREE_SELECT                "picman-tool-free-select"
#define PICMAN_HELP_TOOL_FOREGROUND_SELECT          "picman-tool-foreground-select"
#define PICMAN_HELP_TOOL_FUZZY_SELECT               "picman-tool-fuzzy-select"
#define PICMAN_HELP_TOOL_GEGL                       "picman-tool-gegl"
#define PICMAN_HELP_TOOL_HEAL                       "picman-tool-heal"
#define PICMAN_HELP_TOOL_HUE_SATURATION             "picman-tool-hue-saturation"
#define PICMAN_HELP_TOOL_INK                        "picman-tool-ink"
#define PICMAN_HELP_TOOL_ISCISSORS                  "picman-tool-iscissors"
#define PICMAN_HELP_TOOL_LEVELS                     "picman-tool-levels"
#define PICMAN_HELP_TOOL_MEASURE                    "picman-tool-measure"
#define PICMAN_HELP_TOOL_MOVE                       "picman-tool-move"
#define PICMAN_HELP_TOOL_PATH                       "picman-tool-path"
#define PICMAN_HELP_TOOL_PAINTBRUSH                 "picman-tool-paintbrush"
#define PICMAN_HELP_TOOL_PENCIL                     "picman-tool-pencil"
#define PICMAN_HELP_TOOL_PERSPECTIVE                "picman-tool-perspective"
#define PICMAN_HELP_TOOL_PERSPECTIVE_CLONE          "picman-tool-perspective-clone"
#define PICMAN_HELP_TOOL_POSTERIZE                  "picman-tool-posterize"
#define PICMAN_HELP_TOOL_RECT_SELECT                "picman-tool-rect-select"
#define PICMAN_HELP_TOOL_ROTATE                     "picman-tool-rotate"
#define PICMAN_HELP_TOOL_SCALE                      "picman-tool-scale"
#define PICMAN_HELP_TOOL_SHEAR                      "picman-tool-shear"
#define PICMAN_HELP_TOOL_SMUDGE                     "picman-tool-smudge"
#define PICMAN_HELP_TOOL_TEXT                       "picman-tool-text"
#define PICMAN_HELP_TOOL_THRESHOLD                  "picman-tool-threshold"
#define PICMAN_HELP_TOOL_UNIFIED_TRANSFORM          "picman-tool-unified-transform"
#define PICMAN_HELP_TOOL_VECTORS                    "picman-tool-vectors"
#define PICMAN_HELP_TOOL_ZOOM                       "picman-tool-zoom"

#define PICMAN_HELP_FILTER_REPEAT                   "picman-filter-repeat"
#define PICMAN_HELP_FILTER_RESHOW                   "picman-filter-reshow"
#define PICMAN_HELP_FILTER_RESET_ALL                "picman-filter-reset-all"

#define PICMAN_HELP_TOOLBOX                         "picman-toolbox"
#define PICMAN_HELP_TOOLBOX_COLOR_AREA              "picman-toolbox-color-area"
#define PICMAN_HELP_TOOLBOX_IMAGE_AREA              "picman-toolbox-image-area"
#define PICMAN_HELP_TOOLBOX_INDICATOR_AREA          "picman-toolbox-indicator-area"
#define PICMAN_HELP_TOOLBOX_DEFAULT_COLORS          "picman-toolbox-default-colors"
#define PICMAN_HELP_TOOLBOX_SWAP_COLORS             "picman-toolbox-swap-colors"

#define PICMAN_HELP_BRUSH_DIALOG                    "picman-brush-dialog"
#define PICMAN_HELP_BRUSH_EDIT                      "picman-brush-edit"
#define PICMAN_HELP_BRUSH_OPEN_AS_IMAGE             "picman-brush-open-as-image"
#define PICMAN_HELP_BRUSH_NEW                       "picman-brush-new"
#define PICMAN_HELP_BRUSH_DUPLICATE                 "picman-brush-duplicate"
#define PICMAN_HELP_BRUSH_COPY_LOCATION             "picman-brush-copy-location"
#define PICMAN_HELP_BRUSH_DELETE                    "picman-brush-delete"
#define PICMAN_HELP_BRUSH_REFRESH                   "picman-brush-refresh"

#define PICMAN_HELP_BRUSH_EDITOR_DIALOG             "picman-brush-editor-dialog"
#define PICMAN_HELP_BRUSH_EDITOR_EDIT_ACTIVE        "picman-brush-editor-edit-active"

#define PICMAN_HELP_DYNAMICS_EDITOR_DIALOG          "picman-dynamics-editor-dialog"

#define PICMAN_HELP_TOOL_PRESET_EDITOR_DIALOG       "picman-tool-preset-editor-dialog"

#define PICMAN_HELP_DYNAMICS_DIALOG                 "picman-dynamics-dialog"
#define PICMAN_HELP_DYNAMICS_EDIT                   "picman-dynamics-edit"
#define PICMAN_HELP_DYNAMICS_NEW                    "picman-dynamics-new"
#define PICMAN_HELP_DYNAMICS_DUPLICATE              "picman-dynamics-duplicate"
#define PICMAN_HELP_DYNAMICS_COPY_LOCATION          "picman-dynamics-copy-location"
#define PICMAN_HELP_DYNAMICS_DELETE                 "picman-dynamics-delete"
#define PICMAN_HELP_DYNAMICS_REFRESH                "picman-dynamics-refresh"

#define PICMAN_HELP_PATTERN_DIALOG                  "picman-pattern-dialog"
#define PICMAN_HELP_PATTERN_EDIT                    "picman-pattern-edit"
#define PICMAN_HELP_PATTERN_OPEN_AS_IMAGE           "picman-pattern-open-as-image"
#define PICMAN_HELP_PATTERN_NEW                     "picman-pattern-new"
#define PICMAN_HELP_PATTERN_DUPLICATE               "picman-pattern-duplicate"
#define PICMAN_HELP_PATTERN_COPY_LOCATION           "picman-pattern-copy-location"
#define PICMAN_HELP_PATTERN_DELETE                  "picman-pattern-delete"
#define PICMAN_HELP_PATTERN_REFRESH                 "picman-pattern-refresh"

#define PICMAN_HELP_GRADIENT_DIALOG                 "picman-gradient-dialog"
#define PICMAN_HELP_GRADIENT_EDIT                   "picman-gradient-edit"
#define PICMAN_HELP_GRADIENT_NEW                    "picman-gradient-new"
#define PICMAN_HELP_GRADIENT_DUPLICATE              "picman-gradient-duplicate"
#define PICMAN_HELP_GRADIENT_COPY_LOCATION          "picman-gradient-copy-location"
#define PICMAN_HELP_GRADIENT_DELETE                 "picman-gradient-delete"
#define PICMAN_HELP_GRADIENT_REFRESH                "picman-gradient-refresh"
#define PICMAN_HELP_GRADIENT_SAVE_AS_POV            "picman-gradient-save-as-pov"

#define PICMAN_HELP_GRADIENT_EDITOR_DIALOG          "picman-gradient-editor-dialog"
#define PICMAN_HELP_GRADIENT_EDITOR_LEFT_COLOR      "picman-gradient-editor-left-color"
#define PICMAN_HELP_GRADIENT_EDITOR_LEFT_LOAD       "picman-gradient-editor-left-load"
#define PICMAN_HELP_GRADIENT_EDITOR_LEFT_SAVE       "picman-gradient-editor-left-save"
#define PICMAN_HELP_GRADIENT_EDITOR_RIGHT_COLOR     "picman-gradient-editor-right-color"
#define PICMAN_HELP_GRADIENT_EDITOR_RIGHT_LOAD      "picman-gradient-editor-right-load"
#define PICMAN_HELP_GRADIENT_EDITOR_RIGHT_SAVE      "picman-gradient-editor-right-save"
#define PICMAN_HELP_GRADIENT_EDITOR_BLENDING        "picman-gradient-editor-blending"
#define PICMAN_HELP_GRADIENT_EDITOR_COLORING        "picman-gradient-editor-coloring"
#define PICMAN_HELP_GRADIENT_EDITOR_FLIP            "picman-gradient-editor-flip"
#define PICMAN_HELP_GRADIENT_EDITOR_REPLICATE       "picman-gradient-editor-replicate"
#define PICMAN_HELP_GRADIENT_EDITOR_SPLIT_MIDPOINT  "picman-gradient-editor-split-midpoint"
#define PICMAN_HELP_GRADIENT_EDITOR_SPLIT_UNIFORM   "picman-gradient-editor-split-uniform"
#define PICMAN_HELP_GRADIENT_EDITOR_DELETE          "picman-gradient-editor-delete"
#define PICMAN_HELP_GRADIENT_EDITOR_RECENTER        "picman-gradient-editor-recenter"
#define PICMAN_HELP_GRADIENT_EDITOR_REDISTRIBUTE    "picman-gradient-editor-redistribute"
#define PICMAN_HELP_GRADIENT_EDITOR_BLEND_COLOR     "picman-gradient-editor-blend-color"
#define PICMAN_HELP_GRADIENT_EDITOR_BLEND_OPACITY   "picman-gradient-editor-blend-opacity"
#define PICMAN_HELP_GRADIENT_EDITOR_ZOOM_OUT        "picman-gradient-editor-zoom-out"
#define PICMAN_HELP_GRADIENT_EDITOR_ZOOM_IN         "picman-gradient-editor-zoom-in"
#define PICMAN_HELP_GRADIENT_EDITOR_ZOOM_ALL        "picman-gradient-editor-zoom-all"
#define PICMAN_HELP_GRADIENT_EDITOR_EDIT_ACTIVE     "picman-gradient-editor-edit-active"

#define PICMAN_HELP_PALETTE_DIALOG                  "picman-palette-dialog"
#define PICMAN_HELP_PALETTE_EDIT                    "picman-palette-edit"
#define PICMAN_HELP_PALETTE_NEW                     "picman-palette-new"
#define PICMAN_HELP_PALETTE_DUPLICATE               "picman-palette-duplicate"
#define PICMAN_HELP_PALETTE_COPY_LOCATION           "picman-palette-copy-location"
#define PICMAN_HELP_PALETTE_DELETE                  "picman-palette-delete"
#define PICMAN_HELP_PALETTE_REFRESH                 "picman-palette-refresh"
#define PICMAN_HELP_PALETTE_IMPORT                  "picman-palette-import"
#define PICMAN_HELP_PALETTE_MERGE                   "picman-palette-merge"

#define PICMAN_HELP_PALETTE_EDITOR_DIALOG           "picman-palette-editor-dialog"
#define PICMAN_HELP_PALETTE_EDITOR_NEW              "picman-palette-editor-new"
#define PICMAN_HELP_PALETTE_EDITOR_EDIT             "picman-palette-editor-edit"
#define PICMAN_HELP_PALETTE_EDITOR_DELETE           "picman-palette-editor-delete"
#define PICMAN_HELP_PALETTE_EDITOR_ZOOM_OUT         "picman-palette-editor-zoom-out"
#define PICMAN_HELP_PALETTE_EDITOR_ZOOM_IN          "picman-palette-editor-zoom-in"
#define PICMAN_HELP_PALETTE_EDITOR_ZOOM_ALL         "picman-palette-editor-zoom-all"
#define PICMAN_HELP_PALETTE_EDITOR_EDIT_ACTIVE      "picman-palette-editor-edit-active"

#define PICMAN_HELP_FONT_DIALOG                     "picman-font-dialog"
#define PICMAN_HELP_FONT_REFRESH                    "picman-font-refresh"

#define PICMAN_HELP_BUFFER_DIALOG                   "picman-buffer-dialog"
#define PICMAN_HELP_BUFFER_CUT                      "picman-buffer-cut"
#define PICMAN_HELP_BUFFER_COPY                     "picman-buffer-copy"
#define PICMAN_HELP_BUFFER_PASTE                    "picman-buffer-paste"
#define PICMAN_HELP_BUFFER_PASTE_INTO               "picman-buffer-paste-into"
#define PICMAN_HELP_BUFFER_PASTE_AS_NEW             "picman-buffer-paste-as-new"
#define PICMAN_HELP_BUFFER_DELETE                   "picman-buffer-delete"

#define PICMAN_HELP_TOOL_PRESET_DIALOG              "picman-tool-preset-dialog"
#define PICMAN_HELP_TOOL_PRESET_EDIT                "picman-tool-preset-edit"
#define PICMAN_HELP_TOOL_PRESET_NEW                 "picman-tool-preset-new"
#define PICMAN_HELP_TOOL_PRESET_DUPLICATE           "picman-tool-preset-duplicate"
#define PICMAN_HELP_TOOL_PRESET_COPY_LOCATION       "picman-tool-preset-copy-location"
#define PICMAN_HELP_TOOL_PRESET_DELETE              "picman-tool-preset-delete"
#define PICMAN_HELP_TOOL_PRESET_REFRESH             "picman-tool-preset-refresh"

#define PICMAN_HELP_DOCUMENT_CLEAR                  "picman-document-clear"
#define PICMAN_HELP_DOCUMENT_COPY_LOCATION          "picman-document-copy-location"
#define PICMAN_HELP_DOCUMENT_DIALOG                 "picman-document-dialog"
#define PICMAN_HELP_DOCUMENT_OPEN                   "picman-document-open"
#define PICMAN_HELP_DOCUMENT_REMOVE                 "picman-document-remove"
#define PICMAN_HELP_DOCUMENT_REFRESH                "picman-document-refresh"

#define PICMAN_HELP_TEMPLATE_DIALOG                 "picman-template-dialog"
#define PICMAN_HELP_TEMPLATE_NEW                    "picman-template-new"
#define PICMAN_HELP_TEMPLATE_DUPLICATE              "picman-template-duplicate"
#define PICMAN_HELP_TEMPLATE_EDIT                   "picman-template-edit"
#define PICMAN_HELP_TEMPLATE_IMAGE_NEW              "picman-template-image-new"
#define PICMAN_HELP_TEMPLATE_DELETE                 "picman-template-delete"

#define PICMAN_HELP_TOOL_OPTIONS_DIALOG             "picman-tool-options-dialog"
#define PICMAN_HELP_TOOL_OPTIONS_SAVE               "picman-tool-options-save"
#define PICMAN_HELP_TOOL_OPTIONS_RESTORE            "picman-tool-options-restore"
#define PICMAN_HELP_TOOL_OPTIONS_EDIT               "picman-tool-options-edit"
#define PICMAN_HELP_TOOL_OPTIONS_DELETE             "picman-tool-options-delete"
#define PICMAN_HELP_TOOL_OPTIONS_RESET              "picman-tool-options-reset"

#define PICMAN_HELP_ERRORS_DIALOG                   "picman-errors-dialog"
#define PICMAN_HELP_ERRORS_CLEAR                    "picman-errors-clear"
#define PICMAN_HELP_ERRORS_SAVE                     "picman-errors-save"
#define PICMAN_HELP_ERRORS_SELECT_ALL               "picman-errors-select-all"

#define PICMAN_HELP_PREFS_DIALOG                    "picman-prefs-dialog"
#define PICMAN_HELP_PREFS_NEW_IMAGE                 "picman-prefs-new-image"
#define PICMAN_HELP_PREFS_DEFAULT_GRID              "picman-prefs-default-grid"
#define PICMAN_HELP_PREFS_INTERFACE                 "picman-prefs-interface"
#define PICMAN_HELP_PREFS_HELP                      "picman-prefs-help"
#define PICMAN_HELP_PREFS_THEME                     "picman-prefs-theme"
#define PICMAN_HELP_PREFS_TOOL_OPTIONS              "picman-prefs-tool-options"
#define PICMAN_HELP_PREFS_TOOLBOX                   "picman-prefs-toolbox"
#define PICMAN_HELP_PREFS_INPUT_DEVICES             "picman-prefs-input-devices"
#define PICMAN_HELP_PREFS_INPUT_CONTROLLERS         "picman-prefs-input-controllers"
#define PICMAN_HELP_PREFS_IMAGE_WINDOW              "picman-prefs-image-window"
#define PICMAN_HELP_PREFS_IMAGE_WINDOW_APPEARANCE   "picman-prefs-image-window-appearance"
#define PICMAN_HELP_PREFS_IMAGE_WINDOW_TITLE        "picman-prefs-image-window-title"
#define PICMAN_HELP_PREFS_DISPLAY                   "picman-prefs-display"
#define PICMAN_HELP_PREFS_MONITOR                   "picman-prefs-monitor"
#define PICMAN_HELP_PREFS_COLOR_MANAGEMENT          "picman-prefs-color-management"
#define PICMAN_HELP_PREFS_WINDOW_MANAGEMENT         "picman-prefs-window-management"
#define PICMAN_HELP_PREFS_ENVIRONMENT               "picman-prefs-environment"
#define PICMAN_HELP_PREFS_SESSION                   "picman-prefs-session"
#define PICMAN_HELP_PREFS_FOLDERS                   "picman-prefs-folders"
#define PICMAN_HELP_PREFS_FOLDERS_BRUSHES           "picman-prefs-folders-brushes"
#define PICMAN_HELP_PREFS_FOLDERS_DYNAMICS          "picman-prefs-folders-dynamics"
#define PICMAN_HELP_PREFS_FOLDERS_PATTERNS          "picman-prefs-folders-patterns"
#define PICMAN_HELP_PREFS_FOLDERS_PALETTES          "picman-prefs-folders-palettes"
#define PICMAN_HELP_PREFS_FOLDERS_GRADIENTS         "picman-prefs-folders-gradients"
#define PICMAN_HELP_PREFS_FOLDERS_FONTS             "picman-prefs-folders-fonts"
#define PICMAN_HELP_PREFS_FOLDERS_TOOL_PRESETS      "picman-prefs-folders-tool-presets"
#define PICMAN_HELP_PREFS_FOLDERS_PLUG_INS          "picman-prefs-folders-plug-ins"
#define PICMAN_HELP_PREFS_FOLDERS_SCRIPTS           "picman-prefs-folders-scripts"
#define PICMAN_HELP_PREFS_FOLDERS_MODULES           "picman-prefs-folders-modules"
#define PICMAN_HELP_PREFS_FOLDERS_INTERPRETERS      "picman-prefs-folders-interpreters"
#define PICMAN_HELP_PREFS_FOLDERS_ENVIRONMENT       "picman-prefs-folders-environment"
#define PICMAN_HELP_PREFS_FOLDERS_THEMES            "picman-prefs-folders-themes"

#define PICMAN_HELP_INPUT_DEVICES                   "picman-help-input-devices"
#define PICMAN_HELP_KEYBOARD_SHORTCUTS              "picman-help-keyboard-shortcuts"

#define PICMAN_HELP_INDEXED_PALETTE_DIALOG          "picman-indexed-palette-dialog"
#define PICMAN_HELP_INDEXED_PALETTE_EDIT            "picman-indexed-palette-edit"
#define PICMAN_HELP_INDEXED_PALETTE_ADD             "picman-indexed-palette-add"

#define PICMAN_HELP_POINTER_INFO_DIALOG             "picman-pointer-info-dialog"
#define PICMAN_HELP_POINTER_INFO_SAMPLE_MERGED      "picman-pointer-info-sample-merged"

#define PICMAN_HELP_SAMPLE_POINT_DIALOG             "picman-sample-point-dialog"
#define PICMAN_HELP_SAMPLE_POINT_SAMPLE_MERGED      "picman-sample-point-sample-merged"

#define PICMAN_HELP_DOCK                            "picman-dock"
#define PICMAN_HELP_DOCK_CLOSE                      "picman-dock-close"
#define PICMAN_HELP_DOCK_IMAGE_MENU                 "picman-dock-image-menu"
#define PICMAN_HELP_DOCK_AUTO_BUTTON                "picman-dock-auto-button"
#define PICMAN_HELP_DOCK_CHANGE_SCREEN              "picman-dock-change-screen"
#define PICMAN_HELP_DOCK_SEPARATOR                  "picman-dock-separator"

#define PICMAN_HELP_DOCK_TAB_ADD                    "picman-dock-tab-add"
#define PICMAN_HELP_DOCK_TAB_CLOSE                  "picman-dock-tab-close"
#define PICMAN_HELP_DOCK_TAB_LOCK                   "picman-dock-tab-lock"
#define PICMAN_HELP_DOCK_TAB_MENU                   "picman-dock-tab-menu"
#define PICMAN_HELP_DOCK_TAB_DETACH                 "picman-dock-tab-detach"
#define PICMAN_HELP_DOCK_PREVIEW_SIZE               "picman-dock-preview-size"
#define PICMAN_HELP_DOCK_TAB_STYLE                  "picman-dock-tab-style"
#define PICMAN_HELP_DOCK_VIEW_AS_LIST               "picman-dock-view-as-list"
#define PICMAN_HELP_DOCK_VIEW_AS_GRID               "picman-dock-view-as-grid"
#define PICMAN_HELP_DOCK_SHOW_BUTTON_BAR            "picman-dock-show-button-bar"

#define PICMAN_HELP_ABOUT_DIALOG                    "picman-about-dialog"
#define PICMAN_HELP_COLOR_DIALOG                    "picman-color-dialog"
#define PICMAN_HELP_DEVICE_STATUS_DIALOG            "picman-device-status-dialog"
#define PICMAN_HELP_DISPLAY_FILTER_DIALOG           "picman-display-filter-dialog"
#define PICMAN_HELP_HISTOGRAM_DIALOG                "picman-histogram-dialog"
#define PICMAN_HELP_INFO_DIALOG                     "picman-info-dialog"
#define PICMAN_HELP_MODULE_DIALOG                   "picman-module-dialog"
#define PICMAN_HELP_NAVIGATION_DIALOG               "picman-navigation-dialog"
#define PICMAN_HELP_TEXT_EDITOR_DIALOG              "picman-text-editor-dialog"
#define PICMAN_HELP_TIPS_DIALOG                     "picman-tips-dialog"
#define PICMAN_HELP_UNDO_DIALOG                     "picman-undo-dialog"

#define PICMAN_HELP_EXPORT_DIALOG                   "picman-export-dialog"
#define PICMAN_HELP_EXPORT_CONFIRM_DIALOG           "picman-export-confirm-dialog"
#define PICMAN_HELP_UNIT_DIALOG                     "picman-unit-dialog"

#define PICMAN_HELP_WINDOWS_SHOW_DOCK               "picman-windows-show-dock"
#define PICMAN_HELP_WINDOWS_HIDE_DOCKS              "picman-windows-hide-docks"
#define PICMAN_HELP_WINDOWS_USE_SINGLE_WINDOW_MODE  "picman-windows-use-single-window-mode"
#define PICMAN_HELP_WINDOWS_OPEN_RECENT_DOCK        "picman-windows-open-recent-dock"

#define PICMAN_HELP_HELP                            "picman-help"
#define PICMAN_HELP_HELP_CONTEXT                    "picman-help-context"

#define PICMAN_HELP_COLORDISPLAY_COLORBLIND         "picman-colordisplay-colorblind"
#define PICMAN_HELP_COLORDISPLAY_CONTRAST           "picman-colordisplay-contrast"
#define PICMAN_HELP_COLORDISPLAY_GAMMA              "picman-colordisplay-gamma"
#define PICMAN_HELP_COLORDISPLAY_PICMAN               "picman-colordisplay-picman"
#define PICMAN_HELP_COLORDISPLAY_PROOF              "picman-colordisplay-proof"

#define PICMAN_HELP_COLORSELECTOR_CMYK              "picman-colorselector-cmyk"
#define PICMAN_HELP_COLORSELECTOR_TRIANGLE          "picman-colorselector-triangle"
#define PICMAN_HELP_COLORSELECTOR_WATER             "picman-colorselector-water"

#define PICMAN_HELP_CONTROLLER_KEYBOARD             "picman-controller-keyboard"
#define PICMAN_HELP_CONTROLLER_LINUX_INPUT          "picman-controller-linux-input"
#define PICMAN_HELP_CONTROLLER_MIDI                 "picman-controller-midi"
#define PICMAN_HELP_CONTROLLER_MOUSE                "picman-controller-mouse"
#define PICMAN_HELP_CONTROLLER_WHEEL                "picman-controller-wheel"

#define PICMAN_HELP_CONFIG_USE_GEGL                 "picman-config-use-gegl"


#endif /* __PICMAN_HELP_IDS_H__ */
