/* PICMAN - The GNU Image Manipulation Program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl. */

#include "config.h"

#include <gegl.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "libpicmanbase/picmanbase.h"

#include "pdb-types.h"

#include "core/picman.h"
#include "core/picmanparamspecs.h"

#include "picmanpdb.h"
#include "picmanprocedure.h"
#include "internal-procs.h"


static PicmanValueArray *
fonts_popup_invoker (PicmanProcedure         *procedure,
                     Picman                  *picman,
                     PicmanContext           *context,
                     PicmanProgress          *progress,
                     const PicmanValueArray  *args,
                     GError               **error)
{
  gboolean success = TRUE;
  const gchar *font_callback;
  const gchar *popup_title;
  const gchar *initial_font;

  font_callback = g_value_get_string (picman_value_array_index (args, 0));
  popup_title = g_value_get_string (picman_value_array_index (args, 1));
  initial_font = g_value_get_string (picman_value_array_index (args, 2));

  if (success)
    {
      if (picman->no_interface ||
          ! picman_pdb_lookup_procedure (picman->pdb, font_callback) ||
          ! picman_pdb_dialog_new (picman, context, progress, picman->fonts,
                                 popup_title, font_callback, initial_font,
                                 NULL))
        success = FALSE;
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
fonts_close_popup_invoker (PicmanProcedure         *procedure,
                           Picman                  *picman,
                           PicmanContext           *context,
                           PicmanProgress          *progress,
                           const PicmanValueArray  *args,
                           GError               **error)
{
  gboolean success = TRUE;
  const gchar *font_callback;

  font_callback = g_value_get_string (picman_value_array_index (args, 0));

  if (success)
    {
      if (picman->no_interface ||
          ! picman_pdb_lookup_procedure (picman->pdb, font_callback) ||
          ! picman_pdb_dialog_close (picman, picman->fonts, font_callback))
        success = FALSE;
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
fonts_set_popup_invoker (PicmanProcedure         *procedure,
                         Picman                  *picman,
                         PicmanContext           *context,
                         PicmanProgress          *progress,
                         const PicmanValueArray  *args,
                         GError               **error)
{
  gboolean success = TRUE;
  const gchar *font_callback;
  const gchar *font_name;

  font_callback = g_value_get_string (picman_value_array_index (args, 0));
  font_name = g_value_get_string (picman_value_array_index (args, 1));

  if (success)
    {
      if (picman->no_interface ||
          ! picman_pdb_lookup_procedure (picman->pdb, font_callback) ||
          ! picman_pdb_dialog_set (picman, picman->fonts, font_callback, font_name,
                                 NULL))
        success = FALSE;
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

void
register_font_select_procs (PicmanPDB *pdb)
{
  PicmanProcedure *procedure;

  /*
   * picman-fonts-popup
   */
  procedure = picman_procedure_new (fonts_popup_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-fonts-popup");
  picman_procedure_set_static_strings (procedure,
                                     "picman-fonts-popup",
                                     "Invokes the Picman font selection.",
                                     "This procedure opens the font selection dialog.",
                                     "Sven Neumann <sven@picman.org>",
                                     "Sven Neumann",
                                     "2003",
                                     NULL);
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("font-callback",
                                                       "font callback",
                                                       "The callback PDB proc to call when font selection is made",
                                                       FALSE, FALSE, TRUE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("popup-title",
                                                       "popup title",
                                                       "Title of the font selection dialog",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("initial-font",
                                                       "initial font",
                                                       "The name of the font to set as the first selected",
                                                       FALSE, TRUE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-fonts-close-popup
   */
  procedure = picman_procedure_new (fonts_close_popup_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-fonts-close-popup");
  picman_procedure_set_static_strings (procedure,
                                     "picman-fonts-close-popup",
                                     "Close the font selection dialog.",
                                     "This procedure closes an opened font selection dialog.",
                                     "Sven Neumann <sven@picman.org>",
                                     "Sven Neumann",
                                     "2003",
                                     NULL);
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("font-callback",
                                                       "font callback",
                                                       "The name of the callback registered for this pop-up",
                                                       FALSE, FALSE, TRUE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-fonts-set-popup
   */
  procedure = picman_procedure_new (fonts_set_popup_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-fonts-set-popup");
  picman_procedure_set_static_strings (procedure,
                                     "picman-fonts-set-popup",
                                     "Sets the current font in a font selection dialog.",
                                     "Sets the current font in a font selection dialog.",
                                     "Sven Neumann <sven@picman.org>",
                                     "Sven Neumann",
                                     "2003",
                                     NULL);
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("font-callback",
                                                       "font callback",
                                                       "The name of the callback registered for this pop-up",
                                                       FALSE, FALSE, TRUE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("font-name",
                                                       "font name",
                                                       "The name of the font to set as selected",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);
}
