/* PICMAN - The GNU Image Manipulation Program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl. */

#include "config.h"

#include <string.h>

#include <gegl.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "libpicmanbase/picmanbase.h"
#include "libpicmanconfig/picmanconfig.h"
#include "libpicmanmodule/picmanmodule.h"

#include "libpicmanbase/picmanbase.h"

#include "pdb-types.h"

#include "config/picmanrc.h"
#include "core/picman-utils.h"
#include "core/picman.h"
#include "core/picmanparamspecs.h"
#include "core/picmantemplate.h"

#include "picmanpdb.h"
#include "picmanprocedure.h"
#include "internal-procs.h"


static PicmanValueArray *
picmanrc_query_invoker (PicmanProcedure         *procedure,
                      Picman                  *picman,
                      PicmanContext           *context,
                      PicmanProgress          *progress,
                      const PicmanValueArray  *args,
                      GError               **error)
{
  gboolean success = TRUE;
  PicmanValueArray *return_vals;
  const gchar *token;
  gchar *value = NULL;

  token = g_value_get_string (picman_value_array_index (args, 0));

  if (success)
    {
      if (strlen (token))
        {
          /*  use edit_config because unknown tokens are set there  */
          value = picman_rc_query (PICMAN_RC (picman->edit_config), token);

          if (! value)
            success = FALSE;
        }
      else
        success = FALSE;
    }

  return_vals = picman_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_take_string (picman_value_array_index (return_vals, 1), value);

  return return_vals;
}

static PicmanValueArray *
picmanrc_set_invoker (PicmanProcedure         *procedure,
                    Picman                  *picman,
                    PicmanContext           *context,
                    PicmanProgress          *progress,
                    const PicmanValueArray  *args,
                    GError               **error)
{
  gboolean success = TRUE;
  const gchar *token;
  const gchar *value;

  token = g_value_get_string (picman_value_array_index (args, 0));
  value = g_value_get_string (picman_value_array_index (args, 1));

  if (success)
    {
      if (strlen (token))
        {
          /*  use edit_config because that's the one that gets saved  */
          picman_rc_set_unknown_token (PICMAN_RC (picman->edit_config), token, value);
        }
      else
        success = FALSE;
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
get_default_comment_invoker (PicmanProcedure         *procedure,
                             Picman                  *picman,
                             PicmanContext           *context,
                             PicmanProgress          *progress,
                             const PicmanValueArray  *args,
                             GError               **error)
{
  PicmanValueArray *return_vals;
  gchar *comment = NULL;

  comment = g_strdup (picman_template_get_comment (picman->config->default_image));

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);
  g_value_take_string (picman_value_array_index (return_vals, 1), comment);

  return return_vals;
}

static PicmanValueArray *
get_default_unit_invoker (PicmanProcedure         *procedure,
                          Picman                  *picman,
                          PicmanContext           *context,
                          PicmanProgress          *progress,
                          const PicmanValueArray  *args,
                          GError               **error)
{
  PicmanValueArray *return_vals;
  PicmanUnit unit_id = 0;

  unit_id = picman_get_default_unit ();

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);
  g_value_set_int (picman_value_array_index (return_vals, 1), unit_id);

  return return_vals;
}

static PicmanValueArray *
get_monitor_resolution_invoker (PicmanProcedure         *procedure,
                                Picman                  *picman,
                                PicmanContext           *context,
                                PicmanProgress          *progress,
                                const PicmanValueArray  *args,
                                GError               **error)
{
  PicmanValueArray *return_vals;
  gdouble xres = 0.0;
  gdouble yres = 0.0;

  xres = PICMAN_DISPLAY_CONFIG (picman->config)->monitor_xres;
  yres = PICMAN_DISPLAY_CONFIG (picman->config)->monitor_yres;

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);

  g_value_set_double (picman_value_array_index (return_vals, 1), xres);
  g_value_set_double (picman_value_array_index (return_vals, 2), yres);

  return return_vals;
}

static PicmanValueArray *
get_theme_dir_invoker (PicmanProcedure         *procedure,
                       Picman                  *picman,
                       PicmanContext           *context,
                       PicmanProgress          *progress,
                       const PicmanValueArray  *args,
                       GError               **error)
{
  PicmanValueArray *return_vals;
  gchar *theme_dir = NULL;

  theme_dir = g_strdup (picman_get_theme_dir (picman));

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);
  g_value_take_string (picman_value_array_index (return_vals, 1), theme_dir);

  return return_vals;
}

static PicmanValueArray *
get_color_configuration_invoker (PicmanProcedure         *procedure,
                                 Picman                  *picman,
                                 PicmanContext           *context,
                                 PicmanProgress          *progress,
                                 const PicmanValueArray  *args,
                                 GError               **error)
{
  PicmanValueArray *return_vals;
  gchar *config = NULL;

  config = picman_config_serialize_to_string (PICMAN_CONFIG (picman->config->color_management), NULL);

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);
  g_value_take_string (picman_value_array_index (return_vals, 1), config);

  return return_vals;
}

static PicmanValueArray *
get_module_load_inhibit_invoker (PicmanProcedure         *procedure,
                                 Picman                  *picman,
                                 PicmanContext           *context,
                                 PicmanProgress          *progress,
                                 const PicmanValueArray  *args,
                                 GError               **error)
{
  PicmanValueArray *return_vals;
  gchar *load_inhibit = NULL;

  load_inhibit = g_strdup (picman_module_db_get_load_inhibit (picman->module_db));

  return_vals = picman_procedure_get_return_values (procedure, TRUE, NULL);
  g_value_take_string (picman_value_array_index (return_vals, 1), load_inhibit);

  return return_vals;
}

void
register_picmanrc_procs (PicmanPDB *pdb)
{
  PicmanProcedure *procedure;

  /*
   * picman-picmanrc-query
   */
  procedure = picman_procedure_new (picmanrc_query_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-picmanrc-query");
  picman_procedure_set_static_strings (procedure,
                                     "picman-picmanrc-query",
                                     "Queries the picmanrc file parser for information on a specified token.",
                                     "This procedure is used to locate additional information contained in the picmanrc file considered extraneous to the operation of PICMAN. Plug-ins that need configuration information can expect it will be stored in the user picmanrc file and can use this procedure to retrieve it. This query procedure will return the value associated with the specified token. This corresponds _only_ to entries with the format: (<token> <value>). The value must be a string. Entries not corresponding to this format will cause warnings to be issued on picmanrc parsing and will not be queryable.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1997",
                                     NULL);
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("token",
                                                       "token",
                                                       "The token to query for",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_string ("value",
                                                           "value",
                                                           "The value associated with the queried token",
                                                           FALSE, FALSE, FALSE,
                                                           NULL,
                                                           PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-picmanrc-set
   */
  procedure = picman_procedure_new (picmanrc_set_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-picmanrc-set");
  picman_procedure_set_static_strings (procedure,
                                     "picman-picmanrc-set",
                                     "Sets a picmanrc token to a value and saves it in the picmanrc.",
                                     "This procedure is used to add or change additional information in the picmanrc file that is considered extraneous to the operation of PICMAN. Plug-ins that need configuration information can use this function to store it, and 'picman-picmanrc-query' to retrieve it. This will accept _only_ string values in UTF-8 encoding.",
                                     "Seth Burgess",
                                     "Seth Burgess",
                                     "1999",
                                     NULL);
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("token",
                                                       "token",
                                                       "The token to add or modify",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_string ("value",
                                                       "value",
                                                       "The value to set the token to",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-default-comment
   */
  procedure = picman_procedure_new (get_default_comment_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-default-comment");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-default-comment",
                                     "Get the default image comment as specified in the Preferences.",
                                     "Returns a copy of the default image comment.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1995-1996",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_string ("comment",
                                                           "comment",
                                                           "Default image comment",
                                                           FALSE, FALSE, FALSE,
                                                           NULL,
                                                           PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-default-unit
   */
  procedure = picman_procedure_new (get_default_unit_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-default-unit");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-default-unit",
                                     "Get the default unit (taken from the user's locale).",
                                     "Returns the default unit's integer ID.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1995-1996",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_unit ("unit-id",
                                                         "unit id",
                                                         "Default unit",
                                                         TRUE,
                                                         FALSE,
                                                         PICMAN_UNIT_PIXEL,
                                                         PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-monitor-resolution
   */
  procedure = picman_procedure_new (get_monitor_resolution_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-monitor-resolution");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-monitor-resolution",
                                     "Get the monitor resolution as specified in the Preferences.",
                                     "Returns the resolution of the monitor in pixels/inch. This value is taken from the Preferences (or the windowing system if this is set in the Preferences) and there's no guarantee for the value to be reasonable.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1995-1996",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   g_param_spec_double ("xres",
                                                        "xres",
                                                        "X resolution",
                                                        -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                        PICMAN_PARAM_READWRITE));
  picman_procedure_add_return_value (procedure,
                                   g_param_spec_double ("yres",
                                                        "yres",
                                                        "Y resolution",
                                                        -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                        PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-theme-dir
   */
  procedure = picman_procedure_new (get_theme_dir_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-theme-dir");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-theme-dir",
                                     "Get the directory of the current GUI theme.",
                                     "Returns a copy of the current GUI theme dir.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1995-1996",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_string ("theme-dir",
                                                           "theme dir",
                                                           "The GUI theme dir",
                                                           FALSE, FALSE, FALSE,
                                                           NULL,
                                                           PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-color-configuration
   */
  procedure = picman_procedure_new (get_color_configuration_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-color-configuration");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-color-configuration",
                                     "Get a serialized version of the color management configuration.",
                                     "Returns a string that can be deserialized into a PicmanColorConfig object representing the current color management configuration.",
                                     "Sven Neumann <sven@picman.org>",
                                     "Sven Neumann",
                                     "2005",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_string ("config",
                                                           "config",
                                                           "Serialized color management configuration",
                                                           FALSE, FALSE, FALSE,
                                                           NULL,
                                                           PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-get-module-load-inhibit
   */
  procedure = picman_procedure_new (get_module_load_inhibit_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-get-module-load-inhibit");
  picman_procedure_set_static_strings (procedure,
                                     "picman-get-module-load-inhibit",
                                     "Get the list of modules which should not be loaded.",
                                     "Returns a copy of the list of modules which should not be loaded.",
                                     "Spencer Kimball & Peter Mattis",
                                     "Spencer Kimball & Peter Mattis",
                                     "1995-1996",
                                     NULL);
  picman_procedure_add_return_value (procedure,
                                   picman_param_spec_string ("load-inhibit",
                                                           "load inhibit",
                                                           "The list of modules",
                                                           FALSE, FALSE, FALSE,
                                                           NULL,
                                                           PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);
}
