/* PICMAN - The GNU Image Manipulation Program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl. */

#include "config.h"

#include <cairo.h>

#include <gegl.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "libpicmanbase/picmanbase.h"
#include "libpicmancolor/picmancolor.h"

#include "libpicmanbase/picmanbase.h"

#include "pdb-types.h"

#include "core/picmanchannel-select.h"
#include "core/picmandrawable.h"
#include "core/picmanimage.h"
#include "core/picmanparamspecs.h"

#include "picmanpdb.h"
#include "picmanprocedure.h"
#include "internal-procs.h"

#include "picman-intl.h"


static PicmanValueArray *
by_color_select_invoker (PicmanProcedure         *procedure,
                         Picman                  *picman,
                         PicmanContext           *context,
                         PicmanProgress          *progress,
                         const PicmanValueArray  *args,
                         GError               **error)
{
  gboolean success = TRUE;
  PicmanDrawable *drawable;
  PicmanRGB color;
  gint32 threshold;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius;
  gboolean sample_merged;

  drawable = picman_value_get_drawable (picman_value_array_index (args, 0), picman);
  picman_value_get_rgb (picman_value_array_index (args, 1), &color);
  threshold = g_value_get_int (picman_value_array_index (args, 2));
  operation = g_value_get_enum (picman_value_array_index (args, 3));
  antialias = g_value_get_boolean (picman_value_array_index (args, 4));
  feather = g_value_get_boolean (picman_value_array_index (args, 5));
  feather_radius = g_value_get_double (picman_value_array_index (args, 6));
  sample_merged = g_value_get_boolean (picman_value_array_index (args, 7));

  if (success)
    {
      PicmanImage *image = picman_item_get_image (PICMAN_ITEM (drawable));

      picman_channel_select_by_color (picman_image_get_mask (image), drawable,
                                    sample_merged,
                                    &color,
                                    threshold / 255.0,
                                    FALSE /* don't select transparent */,
                                    PICMAN_SELECT_CRITERION_COMPOSITE,
                                    operation,
                                    antialias,
                                    feather,
                                    feather_radius,
                                    feather_radius);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
by_color_select_full_invoker (PicmanProcedure         *procedure,
                              Picman                  *picman,
                              PicmanContext           *context,
                              PicmanProgress          *progress,
                              const PicmanValueArray  *args,
                              GError               **error)
{
  gboolean success = TRUE;
  PicmanDrawable *drawable;
  PicmanRGB color;
  gint32 threshold;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius_x;
  gdouble feather_radius_y;
  gboolean sample_merged;
  gboolean select_transparent;
  gint32 select_criterion;

  drawable = picman_value_get_drawable (picman_value_array_index (args, 0), picman);
  picman_value_get_rgb (picman_value_array_index (args, 1), &color);
  threshold = g_value_get_int (picman_value_array_index (args, 2));
  operation = g_value_get_enum (picman_value_array_index (args, 3));
  antialias = g_value_get_boolean (picman_value_array_index (args, 4));
  feather = g_value_get_boolean (picman_value_array_index (args, 5));
  feather_radius_x = g_value_get_double (picman_value_array_index (args, 6));
  feather_radius_y = g_value_get_double (picman_value_array_index (args, 7));
  sample_merged = g_value_get_boolean (picman_value_array_index (args, 8));
  select_transparent = g_value_get_boolean (picman_value_array_index (args, 9));
  select_criterion = g_value_get_enum (picman_value_array_index (args, 10));

  if (success)
    {
      PicmanImage *image = picman_item_get_image (PICMAN_ITEM (drawable));

      picman_channel_select_by_color (picman_image_get_mask (image), drawable,
                                    sample_merged,
                                    &color,
                                    threshold / 255.0,
                                    select_transparent,
                                    select_criterion,
                                    operation,
                                    antialias,
                                    feather,
                                    feather_radius_x,
                                    feather_radius_y);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
ellipse_select_invoker (PicmanProcedure         *procedure,
                        Picman                  *picman,
                        PicmanContext           *context,
                        PicmanProgress          *progress,
                        const PicmanValueArray  *args,
                        GError               **error)
{
  gboolean success = TRUE;
  PicmanImage *image;
  gdouble x;
  gdouble y;
  gdouble width;
  gdouble height;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius;

  image = picman_value_get_image (picman_value_array_index (args, 0), picman);
  x = g_value_get_double (picman_value_array_index (args, 1));
  y = g_value_get_double (picman_value_array_index (args, 2));
  width = g_value_get_double (picman_value_array_index (args, 3));
  height = g_value_get_double (picman_value_array_index (args, 4));
  operation = g_value_get_enum (picman_value_array_index (args, 5));
  antialias = g_value_get_boolean (picman_value_array_index (args, 6));
  feather = g_value_get_boolean (picman_value_array_index (args, 7));
  feather_radius = g_value_get_double (picman_value_array_index (args, 8));

  if (success)
    {
      picman_channel_select_ellipse (picman_image_get_mask (image),
                                   (gint) x, (gint) y,
                                   (gint) width, (gint) height,
                                   operation,
                                   antialias,
                                   feather,
                                   feather_radius,
                                   feather_radius,
                                   TRUE);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
free_select_invoker (PicmanProcedure         *procedure,
                     Picman                  *picman,
                     PicmanContext           *context,
                     PicmanProgress          *progress,
                     const PicmanValueArray  *args,
                     GError               **error)
{
  gboolean success = TRUE;
  PicmanImage *image;
  gint32 num_segs;
  const gdouble *segs;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius;

  image = picman_value_get_image (picman_value_array_index (args, 0), picman);
  num_segs = g_value_get_int (picman_value_array_index (args, 1));
  segs = picman_value_get_floatarray (picman_value_array_index (args, 2));
  operation = g_value_get_enum (picman_value_array_index (args, 3));
  antialias = g_value_get_boolean (picman_value_array_index (args, 4));
  feather = g_value_get_boolean (picman_value_array_index (args, 5));
  feather_radius = g_value_get_double (picman_value_array_index (args, 6));

  if (success)
    {
      picman_channel_select_polygon (picman_image_get_mask (image),
                                   _("Free Select"),
                                   num_segs / 2,
                                   (PicmanVector2 *) segs,
                                   operation,
                                   antialias,
                                   feather,
                                   feather_radius,
                                   feather_radius,
                                   TRUE);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
fuzzy_select_invoker (PicmanProcedure         *procedure,
                      Picman                  *picman,
                      PicmanContext           *context,
                      PicmanProgress          *progress,
                      const PicmanValueArray  *args,
                      GError               **error)
{
  gboolean success = TRUE;
  PicmanDrawable *drawable;
  gdouble x;
  gdouble y;
  gint32 threshold;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius;
  gboolean sample_merged;

  drawable = picman_value_get_drawable (picman_value_array_index (args, 0), picman);
  x = g_value_get_double (picman_value_array_index (args, 1));
  y = g_value_get_double (picman_value_array_index (args, 2));
  threshold = g_value_get_int (picman_value_array_index (args, 3));
  operation = g_value_get_enum (picman_value_array_index (args, 4));
  antialias = g_value_get_boolean (picman_value_array_index (args, 5));
  feather = g_value_get_boolean (picman_value_array_index (args, 6));
  feather_radius = g_value_get_double (picman_value_array_index (args, 7));
  sample_merged = g_value_get_boolean (picman_value_array_index (args, 8));

  if (success)
    {
      PicmanImage *image = picman_item_get_image (PICMAN_ITEM (drawable));

      picman_channel_select_fuzzy (picman_image_get_mask (image),
                                 drawable,
                                 sample_merged,
                                 x, y,
                                 threshold / 255.0,
                                 FALSE /* don't select transparent */,
                                 PICMAN_SELECT_CRITERION_COMPOSITE,
                                 operation,
                                 antialias,
                                 feather,
                                 feather_radius,
                                 feather_radius);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
fuzzy_select_full_invoker (PicmanProcedure         *procedure,
                           Picman                  *picman,
                           PicmanContext           *context,
                           PicmanProgress          *progress,
                           const PicmanValueArray  *args,
                           GError               **error)
{
  gboolean success = TRUE;
  PicmanDrawable *drawable;
  gdouble x;
  gdouble y;
  gint32 threshold;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius_x;
  gdouble feather_radius_y;
  gboolean sample_merged;
  gboolean select_transparent;
  gint32 select_criterion;

  drawable = picman_value_get_drawable (picman_value_array_index (args, 0), picman);
  x = g_value_get_double (picman_value_array_index (args, 1));
  y = g_value_get_double (picman_value_array_index (args, 2));
  threshold = g_value_get_int (picman_value_array_index (args, 3));
  operation = g_value_get_enum (picman_value_array_index (args, 4));
  antialias = g_value_get_boolean (picman_value_array_index (args, 5));
  feather = g_value_get_boolean (picman_value_array_index (args, 6));
  feather_radius_x = g_value_get_double (picman_value_array_index (args, 7));
  feather_radius_y = g_value_get_double (picman_value_array_index (args, 8));
  sample_merged = g_value_get_boolean (picman_value_array_index (args, 9));
  select_transparent = g_value_get_boolean (picman_value_array_index (args, 10));
  select_criterion = g_value_get_enum (picman_value_array_index (args, 11));

  if (success)
    {
      PicmanImage *image = picman_item_get_image (PICMAN_ITEM (drawable));

      picman_channel_select_fuzzy (picman_image_get_mask (image),
                                 drawable,
                                 sample_merged,
                                 x, y,
                                 threshold / 255.0,
                                 select_transparent,
                                 select_criterion,
                                 operation,
                                 antialias,
                                 feather,
                                 feather_radius_x,
                                 feather_radius_y);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
rect_select_invoker (PicmanProcedure         *procedure,
                     Picman                  *picman,
                     PicmanContext           *context,
                     PicmanProgress          *progress,
                     const PicmanValueArray  *args,
                     GError               **error)
{
  gboolean success = TRUE;
  PicmanImage *image;
  gdouble x;
  gdouble y;
  gdouble width;
  gdouble height;
  gint32 operation;
  gboolean feather;
  gdouble feather_radius;

  image = picman_value_get_image (picman_value_array_index (args, 0), picman);
  x = g_value_get_double (picman_value_array_index (args, 1));
  y = g_value_get_double (picman_value_array_index (args, 2));
  width = g_value_get_double (picman_value_array_index (args, 3));
  height = g_value_get_double (picman_value_array_index (args, 4));
  operation = g_value_get_enum (picman_value_array_index (args, 5));
  feather = g_value_get_boolean (picman_value_array_index (args, 6));
  feather_radius = g_value_get_double (picman_value_array_index (args, 7));

  if (success)
    {
      picman_channel_select_rectangle (picman_image_get_mask (image),
                                     (gint) x, (gint) y,
                                     (gint) width, (gint) height,
                                     operation,
                                     feather,
                                     feather_radius,
                                     feather_radius,
                                     TRUE);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static PicmanValueArray *
round_rect_select_invoker (PicmanProcedure         *procedure,
                           Picman                  *picman,
                           PicmanContext           *context,
                           PicmanProgress          *progress,
                           const PicmanValueArray  *args,
                           GError               **error)
{
  gboolean success = TRUE;
  PicmanImage *image;
  gdouble x;
  gdouble y;
  gdouble width;
  gdouble height;
  gdouble corner_radius_x;
  gdouble corner_radius_y;
  gint32 operation;
  gboolean antialias;
  gboolean feather;
  gdouble feather_radius_x;
  gdouble feather_radius_y;

  image = picman_value_get_image (picman_value_array_index (args, 0), picman);
  x = g_value_get_double (picman_value_array_index (args, 1));
  y = g_value_get_double (picman_value_array_index (args, 2));
  width = g_value_get_double (picman_value_array_index (args, 3));
  height = g_value_get_double (picman_value_array_index (args, 4));
  corner_radius_x = g_value_get_double (picman_value_array_index (args, 5));
  corner_radius_y = g_value_get_double (picman_value_array_index (args, 6));
  operation = g_value_get_enum (picman_value_array_index (args, 7));
  antialias = g_value_get_boolean (picman_value_array_index (args, 8));
  feather = g_value_get_boolean (picman_value_array_index (args, 9));
  feather_radius_x = g_value_get_double (picman_value_array_index (args, 10));
  feather_radius_y = g_value_get_double (picman_value_array_index (args, 11));

  if (success)
    {
      picman_channel_select_round_rect (picman_image_get_mask (image),
                                      (gint) x, (gint) y,
                                      (gint) width, (gint) height,
                                      corner_radius_x,
                                      corner_radius_y,
                                      operation,
                                      antialias,
                                      feather,
                                      feather_radius_x,
                                      feather_radius_y,
                                      TRUE);
    }

  return picman_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

void
register_selection_tools_procs (PicmanPDB *pdb)
{
  PicmanProcedure *procedure;

  /*
   * picman-by-color-select
   */
  procedure = picman_procedure_new (by_color_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-by-color-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-by-color-select",
                                     "Deprecated: Use 'picman-image-select-color' instead.",
                                     "Deprecated: Use 'picman-image-select-color' instead.",
                                     "",
                                     "",
                                     "",
                                     "picman-image-select-color");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_drawable_id ("drawable",
                                                            "drawable",
                                                            "The affected drawable",
                                                            pdb->picman, FALSE,
                                                            PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_rgb ("color",
                                                    "color",
                                                    "The color to select",
                                                    FALSE,
                                                    NULL,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_int32 ("threshold",
                                                      "threshold",
                                                      "Threshold in intensity levels",
                                                      0, 255, 0,
                                                      PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius",
                                                    "feather radius",
                                                    "Radius for feather operation",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("sample-merged",
                                                     "sample merged",
                                                     "Use the composite image, not the drawable",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-by-color-select-full
   */
  procedure = picman_procedure_new (by_color_select_full_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-by-color-select-full");
  picman_procedure_set_static_strings (procedure,
                                     "picman-by-color-select-full",
                                     "Deprecated: Use 'picman-image-select-color' instead.",
                                     "Deprecated: Use 'picman-image-select-color' instead.",
                                     "David Gowers",
                                     "David Gowers",
                                     "2006",
                                     "picman-image-select-color");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_drawable_id ("drawable",
                                                            "drawable",
                                                            "The affected drawable",
                                                            pdb->picman, FALSE,
                                                            PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_rgb ("color",
                                                    "color",
                                                    "The color to select",
                                                    FALSE,
                                                    NULL,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_int32 ("threshold",
                                                      "threshold",
                                                      "Threshold in intensity levels",
                                                      0, 255, 0,
                                                      PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-x",
                                                    "feather radius x",
                                                    "Radius for feather operation in X direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-y",
                                                    "feather radius y",
                                                    "Radius for feather operation in Y direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("sample-merged",
                                                     "sample merged",
                                                     "Use the composite image, not the drawable",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("select-transparent",
                                                     "select transparent",
                                                     "Whether to consider transparent pixels for selection. If TRUE, transparency is considered as a unique selectable color.",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("select-criterion",
                                                  "select criterion",
                                                  "The criterion used to determine color similarity. SELECT_CRITERION_COMPOSITE is the standard choice.",
                                                  PICMAN_TYPE_SELECT_CRITERION,
                                                  PICMAN_SELECT_CRITERION_COMPOSITE,
                                                  PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-ellipse-select
   */
  procedure = picman_procedure_new (ellipse_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-ellipse-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-ellipse-select",
                                     "Deprecated: Use 'picman-image-select-ellipse' instead.",
                                     "Deprecated: Use 'picman-image-select-ellipse' instead.",
                                     "",
                                     "",
                                     "",
                                     "picman-image-select-ellipse");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_image_id ("image",
                                                         "image",
                                                         "The image",
                                                         pdb->picman, FALSE,
                                                         PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "x coordinate of upper-left corner of ellipse bounding box",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "y coordinate of upper-left corner of ellipse bounding box",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("width",
                                                    "width",
                                                    "The width of the ellipse",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("height",
                                                    "height",
                                                    "The height of the ellipse",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius",
                                                    "feather radius",
                                                    "Radius for feather operation",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-free-select
   */
  procedure = picman_procedure_new (free_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-free-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-free-select",
                                     "Deprecated: Use 'picman-image-select-polygon' instead.",
                                     "Deprecated: Use 'picman-image-select-polygon' instead.",
                                     "",
                                     "",
                                     "",
                                     "picman-image-select-polygon");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_image_id ("image",
                                                         "image",
                                                         "The image",
                                                         pdb->picman, FALSE,
                                                         PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_int32 ("num-segs",
                                                      "num segs",
                                                      "Number of points (count 1 coordinate as two points)",
                                                      2, G_MAXINT32, 2,
                                                      PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_float_array ("segs",
                                                            "segs",
                                                            "Array of points: { p1.x, p1.y, p2.x, p2.y, ..., pn.x, pn.y}",
                                                            PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius",
                                                    "feather radius",
                                                    "Radius for feather operation",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-fuzzy-select
   */
  procedure = picman_procedure_new (fuzzy_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-fuzzy-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-fuzzy-select",
                                     "Deprecated: Use 'picman-image-select-contiguous-color' instead.",
                                     "Deprecated: Use 'picman-image-select-contiguous-color' instead.",
                                     "",
                                     "",
                                     "",
                                     "picman-image-select-contiguous-color");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_drawable_id ("drawable",
                                                            "drawable",
                                                            "The affected drawable",
                                                            pdb->picman, FALSE,
                                                            PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "x coordinate of initial seed fill point: (image coordinates)",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "y coordinate of initial seed fill point: (image coordinates)",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_int32 ("threshold",
                                                      "threshold",
                                                      "Threshold in intensity levels",
                                                      0, 255, 0,
                                                      PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius",
                                                    "feather radius",
                                                    "Radius for feather operation",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("sample-merged",
                                                     "sample merged",
                                                     "Use the composite image, not the drawable",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-fuzzy-select-full
   */
  procedure = picman_procedure_new (fuzzy_select_full_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-fuzzy-select-full");
  picman_procedure_set_static_strings (procedure,
                                     "picman-fuzzy-select-full",
                                     "Deprecated: Use 'picman-image-select-contiguous-color' instead.",
                                     "Deprecated: Use 'picman-image-select-contiguous-color' instead.",
                                     "David Gowers",
                                     "David Gowers",
                                     "2006",
                                     "picman-image-select-contiguous-color");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_drawable_id ("drawable",
                                                            "drawable",
                                                            "The affected drawable",
                                                            pdb->picman, FALSE,
                                                            PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "x coordinate of initial seed fill point: (image coordinates)",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "y coordinate of initial seed fill point: (image coordinates)",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               picman_param_spec_int32 ("threshold",
                                                      "threshold",
                                                      "Threshold in intensity levels",
                                                      0, 255, 0,
                                                      PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-x",
                                                    "feather radius x",
                                                    "Radius for feather operation in X direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-y",
                                                    "feather radius y",
                                                    "Radius for feather operation in Y direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("sample-merged",
                                                     "sample merged",
                                                     "Use the composite image, not the drawable",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("select-transparent",
                                                     "select transparent",
                                                     "Whether to consider transparent pixels for selection. If TRUE, transparency is considered as a unique selectable color.",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("select-criterion",
                                                  "select criterion",
                                                  "The criterion used to determine color similarity. SELECT_CRITERION_COMPOSITE is the standard choice.",
                                                  PICMAN_TYPE_SELECT_CRITERION,
                                                  PICMAN_SELECT_CRITERION_COMPOSITE,
                                                  PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-rect-select
   */
  procedure = picman_procedure_new (rect_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-rect-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-rect-select",
                                     "Deprecated: Use 'picman-image-select-rectangle' instead.",
                                     "Deprecated: Use 'picman-image-select-rectangle' instead.",
                                     "",
                                     "",
                                     "",
                                     "picman-image-select-rectangle");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_image_id ("image",
                                                         "image",
                                                         "The image",
                                                         pdb->picman, FALSE,
                                                         PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "x coordinate of upper-left corner of rectangle",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "y coordinate of upper-left corner of rectangle",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("width",
                                                    "width",
                                                    "The width of the rectangle",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("height",
                                                    "height",
                                                    "The height of the rectangle",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius",
                                                    "feather radius",
                                                    "Radius for feather operation",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * picman-round-rect-select
   */
  procedure = picman_procedure_new (round_rect_select_invoker);
  picman_object_set_static_name (PICMAN_OBJECT (procedure),
                               "picman-round-rect-select");
  picman_procedure_set_static_strings (procedure,
                                     "picman-round-rect-select",
                                     "Deprecated: Use 'picman-image-select-round-rectangle' instead.",
                                     "Deprecated: Use 'picman-image-select-round-rectangle' instead.",
                                     "Martin Nordholts",
                                     "Martin Nordholts",
                                     "2006",
                                     "picman-image-select-round-rectangle");
  picman_procedure_add_argument (procedure,
                               picman_param_spec_image_id ("image",
                                                         "image",
                                                         "The image",
                                                         pdb->picman, FALSE,
                                                         PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "x coordinate of upper-left corner of rectangle",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "y coordinate of upper-left corner of rectangle",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("width",
                                                    "width",
                                                    "The width of the rectangle",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("height",
                                                    "height",
                                                    "The height of the rectangle",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("corner-radius-x",
                                                    "corner radius x",
                                                    "The corner radius in X direction",
                                                    0, PICMAN_MAX_IMAGE_SIZE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("corner-radius-y",
                                                    "corner radius y",
                                                    "The corner radius in Y direction",
                                                    0, PICMAN_MAX_IMAGE_SIZE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_enum ("operation",
                                                  "operation",
                                                  "The selection operation",
                                                  PICMAN_TYPE_CHANNEL_OPS,
                                                  PICMAN_CHANNEL_OP_ADD,
                                                  PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("antialias",
                                                     "antialias",
                                                     "Antialiasing",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_boolean ("feather",
                                                     "feather",
                                                     "Feather option for selections",
                                                     FALSE,
                                                     PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-x",
                                                    "feather radius x",
                                                    "Radius for feather operation in X direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_procedure_add_argument (procedure,
                               g_param_spec_double ("feather-radius-y",
                                                    "feather radius y",
                                                    "Radius for feather operation in Y direction",
                                                    0, G_MAXDOUBLE, 0,
                                                    PICMAN_PARAM_READWRITE));
  picman_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);
}
