#!/usr/bin/perl -w

use lib '../../tools/pdbgen';

require 'util.pl';

*write_file = \&Picman::CodeGen::util::write_file;
*FILE_EXT   = \$Picman::CodeGen::util::FILE_EXT;

$destdir = ".";
$builddir = ".";

$ignorefile = ".gitignore";
$rcfile     = "picmanrc.common";

$outmk = "$builddir/Makefile.am$FILE_EXT";
$outignore = "$builddir/$ignorefile$FILE_EXT";
$outrc = "$builddir/$rcfile$FILE_EXT";

open MK, "> $outmk";
open IGNORE, "> $outignore";
open RC, "> $outrc";

require 'plugin-defs.pl';

$bins = ""; $opts = "";

foreach (sort keys %plugins) {
    $bins .= "\t";
    if (exists $plugins{$_}->{optional}) {
        my $makename = $_;
        $makename =~ s/-/_/g;
	$bins .= "\$(\U$makename\E)";
	$opts .= "\t$_ \\\n";
    }
    else {
	$bins .= $_;
    }
    $bins .= " \\\n";
}

$extra = "";
foreach (@extra) { $extra .= "\t$_\t\\\n" }
if ($extra) {
    $extra =~ s/\t\\\n$//s;
    $extra = "\t\\\n$extra";
}

foreach ($bins, $opts) { s/ \\\n$//s }

print MK <<EOT;


## ---------------------------------------------------------
## This file is autogenerated by mkgen.pl and plugin-defs.pl
## ---------------------------------------------------------

## Modify those two files instead of this one; for most
## plug-ins you should only need to modify plugin-defs.pl.

if OS_WIN32
mwindows = -mwindows
else
libm = -lm
endif

if HAVE_WINDRES
include \$(top_srcdir)/build/windows/picmanrc-plug-ins.rule
include $rcfile
endif

libpicman = \$(top_builddir)/libpicman/libpicman-\$(PICMAN_API_VERSION).la
libpicmanbase = \$(top_builddir)/libpicmanbase/libpicmanbase-\$(PICMAN_API_VERSION).la
libpicmancolor = \$(top_builddir)/libpicmancolor/libpicmancolor-\$(PICMAN_API_VERSION).la
libpicmanconfig = \$(top_builddir)/libpicmanconfig/libpicmanconfig-\$(PICMAN_API_VERSION).la
libpicmanmath = \$(top_builddir)/libpicmanmath/libpicmanmath-\$(PICMAN_API_VERSION).la \$(libm)
libpicmanmodule = \$(top_builddir)/libpicmanmodule/libpicmanmodule-\$(PICMAN_API_VERSION).la
libpicmanui = \$(top_builddir)/libpicman/libpicmanui-\$(PICMAN_API_VERSION).la
libpicmanwidgets = \$(top_builddir)/libpicmanwidgets/libpicmanwidgets-\$(PICMAN_API_VERSION).la


AM_LDFLAGS = \$(mwindows)

libexecdir = \$(picmanplugindir)/plug-ins

EXTRA_DIST = \\
	mkgen.pl	\\
	plugin-defs.pl$extra	\\
	$rcfile

INCLUDES = \\
	-I\$(top_srcdir)	\\
	\$(GTK_CFLAGS)	\\
	\$(GEGL_CFLAGS)	\\
	-I\$(includedir)

libexec_PROGRAMS = \\
$bins

EXTRA_PROGRAMS = \\
$opts

install-\%: \%
	\@\$(NORMAL_INSTALL)
	\$(mkinstalldirs) \$(DESTDIR)\$(libexecdir)
	\@p=\$<; p1=`echo \$\$p|sed 's/\$(EXEEXT)\$\$//'`; \\
	if test -f \$\$p \\
	   || test -f \$\$p1 \\
	; then \\
	  f=`echo "\$\$p1" | sed 's,^.*/,,;\$(transform);s/\$\$/\$(EXEEXT)/'`; \\
	  echo " \$(INSTALL_PROGRAM_ENV) \$(LIBTOOL) --mode=install \$(INSTALL_PROGRAM) \$\$p \$(DESTDIR)\$(libexecdir)/\$\$f"; \\
	  \$(INSTALL_PROGRAM_ENV) \$(LIBTOOL) --mode=install \$(INSTALL_PROGRAM) \$\$p \$(DESTDIR)\$(libexecdir)/\$\$f || exit 1; \\
	else :; fi
EOT

print IGNORE <<EOT;
/.deps
/.libs
/Makefile
/Makefile.in
EOT

foreach (sort keys %plugins) {
    my $makename = $_;
    $makename =~ s/-/_/g;

    my $libpicman = "";

    if (exists $plugins{$_}->{ui}) {
        $libpicman .= "\$(libpicmanui)";
        $libpicman .= "\t\t\\\n\t\$(libpicmanwidgets)";
	$libpicman .= "\t\\\n\t\$(libpicmanmodule)";
	$libpicman .= "\t\\\n\t";
    }

    $libpicman .= "\$(libpicman)";
    $libpicman .= "\t\t\\\n\t\$(libpicmanmath)";
    $libpicman .= "\t\t\\\n\t\$(libpicmanconfig)";
    $libpicman .= "\t\\\n\t\$(libpicmancolor)";
    $libpicman .= "\t\t\\\n\t\$(libpicmanbase)";

    my $glib;
    if (exists $plugins{$_}->{ui}) {
	$glib = "\$(GTK_LIBS)\t\t\\"
    } else {
	$glib = "\$(CAIRO_LIBS)\t\t\\\n\t\$(GDK_PIXBUF_LIBS)\t\\"
    }

    if (exists $plugins{$_}->{gegl}) {
	$glib .= "\n\t\$(GEGL_LIBS)\t\t\\";
    }

    my $optlib = "";

    if (exists $plugins{$_}->{optional}) {
	if (exists $plugins{$_}->{libs}) {
		$optlib = "\n\t\$(" . $plugins{$_}->{libs} . ")\t\t\\";
	}
    }

    if (exists $plugins{$_}->{cflags}) {
	my $cflags = $plugins{$_}->{cflags};
	my $cflagsvalue = $cflags =~ /FLAGS/ ? "\$($cflags)" : $cflags;

	print MK <<EOT;

${makename}_CFLAGS = $cflagsvalue
EOT
    }

    my $deplib = "\$(RT_LIBS)\t\t\\\n\t\$(INTLLIBS)";
    if (exists $plugins{$_}->{libdep}) {
	my @lib = split(/:/, $plugins{$_}->{libdep});
	foreach $lib (@lib) {
	    $deplib = "\$(\U$lib\E_LIBS)\t\t\\\n\t$deplib";
	}
    }

    my $rclib = "\$(${makename}_RC)";

    print MK <<EOT;

${makename}_SOURCES = \\
	$_.c

${makename}_LDADD = \\
	$libpicman		\\
	$glib$optlib
	$deplib		\\
	$rclib
EOT

     print RC <<EOT;
${makename}_RC = $_.rc.o
EOT

    print IGNORE "/$_\n";
    print IGNORE "/$_.exe\n";
}

close RC;
close MK;
close IGNORE;

&write_file($outmk, $destdir);
&write_file($outignore, $destdir);
&write_file($outrc, $destdir);

