/* LIBPICMAN - The PICMAN Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * picmandrawabletransform_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__PICMAN_H_INSIDE__) && !defined (PICMAN_COMPILATION)
#error "Only <libpicman/picman.h> can be included directly."
#endif

#ifndef __PICMAN_DRAWABLE_TRANSFORM_PDB_H__
#define __PICMAN_DRAWABLE_TRANSFORM_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


PICMAN_DEPRECATED_FOR(picman_item_transform_flip_simple)
gint32 picman_drawable_transform_flip_simple         (gint32                 drawable_ID,
                                                    PicmanOrientationType    flip_type,
                                                    gboolean               auto_center,
                                                    gdouble                axis,
                                                    gboolean               clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_flip)
gint32 picman_drawable_transform_flip                (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    gboolean               clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_flip)
gint32 picman_drawable_transform_flip_default        (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    gboolean               interpolate,
                                                    gboolean               clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_perspective)
gint32 picman_drawable_transform_perspective         (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    gdouble                x2,
                                                    gdouble                y2,
                                                    gdouble                x3,
                                                    gdouble                y3,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_perspective)
gint32 picman_drawable_transform_perspective_default (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    gdouble                x2,
                                                    gdouble                y2,
                                                    gdouble                x3,
                                                    gdouble                y3,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_rotate_simple)
gint32 picman_drawable_transform_rotate_simple       (gint32                 drawable_ID,
                                                    PicmanRotationType       rotate_type,
                                                    gboolean               auto_center,
                                                    gint                   center_x,
                                                    gint                   center_y,
                                                    gboolean               clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_rotate)
gint32 picman_drawable_transform_rotate              (gint32                 drawable_ID,
                                                    gdouble                angle,
                                                    gboolean               auto_center,
                                                    gint                   center_x,
                                                    gint                   center_y,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_rotate)
gint32 picman_drawable_transform_rotate_default      (gint32                 drawable_ID,
                                                    gdouble                angle,
                                                    gboolean               auto_center,
                                                    gint                   center_x,
                                                    gint                   center_y,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_scale)
gint32 picman_drawable_transform_scale               (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_scale)
gint32 picman_drawable_transform_scale_default       (gint32                 drawable_ID,
                                                    gdouble                x0,
                                                    gdouble                y0,
                                                    gdouble                x1,
                                                    gdouble                y1,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_shear)
gint32 picman_drawable_transform_shear               (gint32                 drawable_ID,
                                                    PicmanOrientationType    shear_type,
                                                    gdouble                magnitude,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_shear)
gint32 picman_drawable_transform_shear_default       (gint32                 drawable_ID,
                                                    PicmanOrientationType    shear_type,
                                                    gdouble                magnitude,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_2d)
gint32 picman_drawable_transform_2d                  (gint32                 drawable_ID,
                                                    gdouble                source_x,
                                                    gdouble                source_y,
                                                    gdouble                scale_x,
                                                    gdouble                scale_y,
                                                    gdouble                angle,
                                                    gdouble                dest_x,
                                                    gdouble                dest_y,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_2d)
gint32 picman_drawable_transform_2d_default          (gint32                 drawable_ID,
                                                    gdouble                source_x,
                                                    gdouble                source_y,
                                                    gdouble                scale_x,
                                                    gdouble                scale_y,
                                                    gdouble                angle,
                                                    gdouble                dest_x,
                                                    gdouble                dest_y,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_matrix)
gint32 picman_drawable_transform_matrix              (gint32                 drawable_ID,
                                                    gdouble                coeff_0_0,
                                                    gdouble                coeff_0_1,
                                                    gdouble                coeff_0_2,
                                                    gdouble                coeff_1_0,
                                                    gdouble                coeff_1_1,
                                                    gdouble                coeff_1_2,
                                                    gdouble                coeff_2_0,
                                                    gdouble                coeff_2_1,
                                                    gdouble                coeff_2_2,
                                                    PicmanTransformDirection transform_direction,
                                                    PicmanInterpolationType  interpolation,
                                                    gboolean               supersample,
                                                    gint                   recursion_level,
                                                    PicmanTransformResize    clip_result);
PICMAN_DEPRECATED_FOR(picman_item_transform_matrix)
gint32 picman_drawable_transform_matrix_default      (gint32                 drawable_ID,
                                                    gdouble                coeff_0_0,
                                                    gdouble                coeff_0_1,
                                                    gdouble                coeff_0_2,
                                                    gdouble                coeff_1_0,
                                                    gdouble                coeff_1_1,
                                                    gdouble                coeff_1_2,
                                                    gdouble                coeff_2_0,
                                                    gdouble                coeff_2_1,
                                                    gdouble                coeff_2_2,
                                                    gboolean               interpolate,
                                                    PicmanTransformResize    clip_result);


G_END_DECLS

#endif /* __PICMAN_DRAWABLE_TRANSFORM_PDB_H__ */
