/* LIBPICMAN - The PICMAN Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * picmancolor_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__PICMAN_H_INSIDE__) && !defined (PICMAN_COMPILATION)
#error "Only <libpicman/picman.h> can be included directly."
#endif

#ifndef __PICMAN_COLOR_PDB_H__
#define __PICMAN_COLOR_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


gboolean picman_brightness_contrast (gint32                drawable_ID,
                                   gint                  brightness,
                                   gint                  contrast);
gboolean picman_levels              (gint32                drawable_ID,
                                   PicmanHistogramChannel  channel,
                                   gint                  low_input,
                                   gint                  high_input,
                                   gdouble               gamma,
                                   gint                  low_output,
                                   gint                  high_output);
PICMAN_DEPRECATED_FOR(picman_levels_stretch)
gboolean picman_levels_auto         (gint32                drawable_ID);
gboolean picman_levels_stretch      (gint32                drawable_ID);
gboolean picman_posterize           (gint32                drawable_ID,
                                   gint                  levels);
gboolean picman_desaturate          (gint32                drawable_ID);
gboolean picman_desaturate_full     (gint32                drawable_ID,
                                   PicmanDesaturateMode    desaturate_mode);
gboolean picman_equalize            (gint32                drawable_ID,
                                   gboolean              mask_only);
gboolean picman_invert              (gint32                drawable_ID);
gboolean picman_curves_spline       (gint32                drawable_ID,
                                   PicmanHistogramChannel  channel,
                                   gint                  num_points,
                                   const guint8         *control_pts);
gboolean picman_curves_explicit     (gint32                drawable_ID,
                                   PicmanHistogramChannel  channel,
                                   gint                  num_bytes,
                                   const guint8         *curve);
gboolean picman_color_balance       (gint32                drawable_ID,
                                   PicmanTransferMode      transfer_mode,
                                   gboolean              preserve_lum,
                                   gdouble               cyan_red,
                                   gdouble               magenta_green,
                                   gdouble               yellow_blue);
gboolean picman_colorize            (gint32                drawable_ID,
                                   gdouble               hue,
                                   gdouble               saturation,
                                   gdouble               lightness);
gboolean picman_histogram           (gint32                drawable_ID,
                                   PicmanHistogramChannel  channel,
                                   gint                  start_range,
                                   gint                  end_range,
                                   gdouble              *mean,
                                   gdouble              *std_dev,
                                   gdouble              *median,
                                   gdouble              *pixels,
                                   gdouble              *count,
                                   gdouble              *percentile);
gboolean picman_hue_saturation      (gint32                drawable_ID,
                                   PicmanHueRange          hue_range,
                                   gdouble               hue_offset,
                                   gdouble               lightness,
                                   gdouble               saturation);
gboolean picman_threshold           (gint32                drawable_ID,
                                   gint                  low_threshold,
                                   gint                  high_threshold);


G_END_DECLS

#endif /* __PICMAN_COLOR_PDB_H__ */
