/* LIBPICMAN - The PICMAN Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * picmangradients_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__PICMAN_H_INSIDE__) && !defined (PICMAN_COMPILATION)
#error "Only <libpicman/picman.h> can be included directly."
#endif

#ifndef __PICMAN_GRADIENTS_PDB_H__
#define __PICMAN_GRADIENTS_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


gboolean picman_gradients_refresh           (void);
gchar**  picman_gradients_get_list          (const gchar    *filter,
                                           gint           *num_gradients);
PICMAN_DEPRECATED_FOR(picman_gradient_get_uniform_samples)
gdouble* picman_gradients_sample_uniform    (gint            num_samples,
                                           gboolean        reverse);
PICMAN_DEPRECATED_FOR(picman_gradient_get_custom_samples)
gdouble* picman_gradients_sample_custom     (gint            num_samples,
                                           const gdouble  *positions,
                                           gboolean        reverse);
PICMAN_DEPRECATED_FOR(picman_gradient_get_uniform_samples)
gchar*   picman_gradients_get_gradient_data (const gchar    *name,
                                           gint            sample_size,
                                           gboolean        reverse,
                                           gint           *width,
                                           gdouble       **grad_data);


G_END_DECLS

#endif /* __PICMAN_GRADIENTS_PDB_H__ */
